from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
BLUE=HexColor('#246a8b');INK=HexColor('#1d2936');MUTED=HexColor('#667681');PAPER=HexColor('#f5f4ef');LINE=HexColor('#d4dce0')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=BLUE,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=BLUE,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(BLUE);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'PlateCheck · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · PERSONAL MVP','c'),Spacer(1,20),p('PlateCheck','t'),Spacer(1,10),p('부품 치수와 출력판을 대조해<br/>한 판 생산량과 필요한 판 수를 계산하는 도구','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-12-0858-platecheck')],[p('대상 고객'),p('취미용 FDM 사용자·소형 메이커')],[p('가격'),p('1회 ₩9,900')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,BLUE),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','PlateCheck는 부품의 직사각형 바운딩박스와 출력판 크기, 간격을 입력받아 0°·90° 격자 배치 용량과 필요한 출력판 수를 계산하는 브라우저 도구다.'),sec('2. 대상 고객','슬라이서를 열기 전에 다품종 소형 부품의 배치 가능성과 대략적인 생산 판 수를 빠르게 확인하려는 취미용 FDM 사용자와 소형 메이커다.'),sec('3. 해결하는 문제','부품 치수가 출력판을 넘거나 회전하면 더 많이 배치되는 상황을 반복 계산하기 번거롭다. 단순한 치수 단계에서 불가능한 작업과 예상 판 수를 먼저 걸러낼 수 있다.'),sec('4. 핵심 기능','① 부품·출력판 치수와 간격 검증 ② 0°·90° 격자 배치 용량 비교 ③ 필요 수량에 따른 출력판 수 계산'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 부품과 출력판 치수, 간격, 필요 수량을 입력하고 추천 회전 방향과 한 판 용량을 확인한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·격자 용량·판 수 계산 엔진 → localStorage. 서버 계정이나 외부 데이터 전송이 없는 단일 사용자 구조다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 신규 서보 마운트 배치 분석을 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 입력 정제, 치수·간격 검증, 격자 용량, 회전 선택, 배치 불가, 필요 판 수, 삭제를 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 길이와 숫자 범위를 제한하고 HTML 이스케이프를 적용한다. 비밀값과 외부 전송은 없다. 실제 슬라이서의 유효영역·브림·서포트·헤드 간섭은 계산하지 않는다.'),sec('11. 가격과 수익 모델','1회 ₩9,900 구매. 광고·계정 없이 빠르게 배치 가능성과 생산량을 확인하는 오프라인 도구로 판매한다.'),sec('12. 첫 고객 확보 방법','3D 프린팅 커뮤니티에 무료 출력판 계산 샘플을 공개하고, 자주 출력하는 클립·브래킷 작업 20건의 계산 시간을 비교해 구매 전환을 검증한다.'),sec('13. 개선 계획','1) 사용자 정의 프린터 프로필 2) 혼합 부품 배치 3) 비직사각형 네스팅 4) JSON 백업 5) 슬라이서 내보내기.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('8/10'),p('반복 출력 전 배치 계산이 자주 발생한다.')],[p('하루 내 완성도'),p('9/10'),p('검증·회전 비교·판 수 흐름을 완성했다.')],[p('판매 가능성'),p('8/10'),p('메이커에게 명확한 시간 절약 가치를 준다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('8/10'),p('슬라이서 전 치수 단계 판단에 집중한다.')],[p('확장 가능성'),p('8/10'),p('혼합 네스팅과 프린터 프로필로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),BLUE),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.4/10','h'),p('3D 프린팅 사용자에게 반복되는 계산을 좁은 기능으로 해결한다. 유료화 전에는 단순 격자 배치만으로 충분한 사용자 비율을 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 개인 사용과 고객 인터뷰용 MVP로 사용할 수 있다. 실제 출력 전에는 반드시 슬라이서에서 최종 배치를 확인해야 한다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='PlateCheck MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
