from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
BLUE=HexColor('#173f68');INK=HexColor('#1d2433');MUTED=HexColor('#697180');PAPER=HexColor('#f3f0ea');LINE=HexColor('#dad7cf')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=BLUE,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=BLUE,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(BLUE);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'ProofPocket · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · PERSONAL MVP','c'),Spacer(1,20),p('ProofPocket','t'),Spacer(1,10),p('보증 만료일과 청구 증빙을<br/>한곳에서 관리하는 로컬 우선 도구','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-08-0900-proofpocket')],[p('대상 고객'),p('전자기기·가전·메이커 도구 보유자')],[p('가격'),p('1회 ₩8,900')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,BLUE),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','ProofPocket은 구매일과 보증기간으로 만료일을 계산하고 영수증·시리얼 보유 상태를 함께 보여 주는 브라우저 기반 개인 도구다.'),sec('2. 대상 고객','전자기기, 가전, 3D 프린터와 취미 장비를 여러 개 보유해 보증 정보를 기억하기 어려운 개인 사용자다.'),sec('3. 해결하는 문제','영수증과 보증기간이 흩어져 있으면 고장 후 만료 사실이나 증빙 부족을 뒤늦게 알게 된다. 제품 가치가 높을수록 놓친 보증의 손실도 커진다.'),sec('4. 핵심 기능','① 검증된 구매품 등록 ② 만료일까지 남은 날짜와 보호 가치 큐 ③ 영수증·시리얼 청구 준비도 체크'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 제품을 등록하고 만료 위험 순서를 확인한 뒤 영수증·시리얼 보유 버튼으로 준비 상태를 갱신한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·보증기간 계산 엔진 → localStorage. 실제 영수증 파일이나 시리얼 값은 수집하지 않는다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 제품을 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 월말 날짜 계산, 입력 검증, 만료 위험, 보호 가치 집계, 큐 정렬, 증빙 토글을 확인했다. HTTP 200과 Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 범위 제한과 HTML 이스케이프를 적용한다. 비밀값과 외부 전송은 없다. 제조사 약관을 자동 판정하지 않으므로 실제 청구 전 공식 약관 확인이 필요하다.'),sec('11. 가격과 수익 모델','1회 ₩8,900 라이선스. 개인 데이터가 로컬에 남는 점과 회수 가능한 제품 가치를 판매 포인트로 삼는다.'),sec('12. 첫 고객 확보 방법','전자기기·메이커 커뮤니티에 무료 보증 만료 체크 템플릿을 배포하고, 5개 이상 제품을 등록한 사용자를 유료 버전으로 전환한다.'),sec('13. 개선 계획','1) JSON 백업 2) 기기 내 알림 3) 제조사별 약관 템플릿 4) 암호화된 영수증 첨부 5) 기기간 선택 동기화.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('8/10'),p('고가 제품일수록 놓친 보증의 손실이 명확하다.')],[p('하루 내 완성도'),p('9/10'),p('등록·만료 계산·준비도 흐름을 완성했다.')],[p('판매 가능성'),p('7/10'),p('저가 1회 구매로 진입 장벽이 낮다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('7/10'),p('만료일과 증빙 준비도를 함께 관리한다.')],[p('확장 가능성'),p('8/10'),p('알림·백업·약관 템플릿으로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),BLUE),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.0/10','h'),p('개인정보를 최소화하면서 명확한 비용 손실을 예방하는 작은 도구다. 판매 전에는 제조사별 보증 규칙의 다양성과 사용자의 알림 수요를 인터뷰로 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 개인 로컬 사용과 고객 인터뷰용 데모로 사용할 수 있다. 보증 만료일은 입력값 기반 참고 정보이며 공식 약관을 대체하지 않는다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='ProofPocket MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
