(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.ProofEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const categories=['전자기기','가전','취미용품','생활용품'];const clean=(v,n=80)=>String(v??'').trim().replace(/[<>]/g,'').slice(0,n);const dateOk=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T00:00:00'));const uid=()=>Math.random().toString(36).slice(2,10);
function addMonths(date,months){const d=new Date(date+'T00:00:00Z'),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+months);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10)}
function normalize(raw){const name=clean(raw.name,40),store=clean(raw.store,40),category=clean(raw.category,20),purchaseDate=clean(raw.purchaseDate,10),months=Number(raw.warrantyMonths),price=Number(raw.price);if(name.length<2)throw Error('제품명은 2자 이상 입력하세요.');if(store.length<2)throw Error('구매처는 2자 이상 입력하세요.');if(!categories.includes(category))throw Error('지원 카테고리만 선택하세요.');if(!dateOk(purchaseDate))throw Error('구매일을 확인하세요.');if(!Number.isInteger(months)||months<1||months>120)throw Error('보증기간은 1~120개월이어야 합니다.');if(!Number.isFinite(price)||price<1000||price>50000000)throw Error('구매가는 1,000~50,000,000원이어야 합니다.');return{id:clean(raw.id)||uid(),name,store,category,purchaseDate,warrantyMonths:months,price:Math.round(price),hasReceipt:raw.hasReceipt===true||raw.hasReceipt==='on',hasSerial:raw.hasSerial===true||raw.hasSerial==='on',status:'active'}}
const days=(a,b)=>Math.floor((Date.parse(b+'T00:00:00Z')-Date.parse(a+'T00:00:00Z'))/86400000);
function enrich(item,today){const expiry=addMonths(item.purchaseDate,item.warrantyMonths),daysLeft=days(today,expiry),risk=daysLeft<0?'expired':daysLeft<=30?'urgent':daysLeft<=90?'soon':'active',ready=[item.hasReceipt,item.hasSerial].filter(Boolean).length;return{...item,expiry,daysLeft,risk,ready,readiness:ready===2?'청구 준비 완료':ready===1?'증빙 1개 필요':'증빙 2개 필요'}}
function dashboard(items,today){const rows=items.filter(x=>x.status==='active').map(x=>enrich(x,today)).sort((a,b)=>a.daysLeft-b.daysLeft);return{total:rows.length,urgent:rows.filter(x=>x.risk==='urgent').length,protectedValue:rows.filter(x=>x.risk!=='expired').reduce((s,x)=>s+x.price,0),missingProof:rows.filter(x=>x.ready<2).length,rows}}
function toggleProof(items,id,key){if(!['hasReceipt','hasSerial'].includes(key))throw Error('허용되지 않은 증빙 항목입니다.');if(!items.some(x=>x.id===id))throw Error('제품을 찾을 수 없습니다.');return items.map(x=>x.id===id?{...x,[key]:!x[key]}:x)}
return{categories,addMonths,normalize,enrich,dashboard,toggleProof};});
