from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
GREEN=HexColor('#24735d');INK=HexColor('#202b27');MUTED=HexColor('#65736d');PAPER=HexColor('#f6f4ef');LINE=HexColor('#d4dcd8')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=GREEN,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=GREEN,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(GREEN);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'BatchBalance · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · BUSINESS MVP','c'),Spacer(1,20),p('BatchBalance','t'),Spacer(1,10),p('생산 배치의 수율 편차와 폐기 비용을<br/>한눈에 찾는 로컬 우선 시스템','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-12-1600-batchbalance')],[p('대상 고객'),p('소형 베이커리·디저트 공방')],[p('가격'),p('사업장당 월 ₩17,000')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,GREEN),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','BatchBalance은 계획·완제품·폐기 수량과 원가를 등록하고, 수율과 폐기 비용을 계산하는 브라우저 기반 업무 시스템이다.'),sec('2. 대상 고객','매일 여러 제품을 배치 단위로 생산하는 소형 베이커리와 디저트 공방이다.'),sec('3. 해결하는 문제','계획 대비 실제 생산량과 폐기를 기록하지 않으면 손실 원인을 찾기 어렵다. 낮은 수율과 폐기 비용을 큐로 보여 주면 개선 대상을 먼저 찾을 수 있다.'),sec('4. 핵심 기능','① 검증된 생산 배치 등록 ② 수율·폐기비 계산 ③ 손실 위험 큐'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 생산 후 계획·완제품·폐기 수량을 등록하고 낮은 수율의 배치를 검토 완료 처리한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·수율·폐기비 계산 엔진 → localStorage. 외부 전송과 관리자 화면이 없는 단일 사업장 구조다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 신규 생산 배치를 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 입력 정제, 수량 상한과 합계 검증, 수율·미분류·폐기비·평균 수율 계산, 검토 상태 전환을 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 길이·숫자 범위 제한과 HTML 이스케이프를 적용한다. 고객 개인정보·비밀번호·결제정보를 입력하지 않도록 안내한다. 다중 사용자 동기화와 감사 로그는 포함하지 않는다.'),sec('11. 가격과 수익 모델','사업장당 월 ₩17,000 구독. 폐기와 수율 편차로 생기는 원가 손실을 줄이는 가치를 판매 포인트로 삼는다.'),sec('12. 첫 고객 확보 방법','동네 베이커리와 디저트 공방 10곳에 무료 수율 기록표를 제공하고, 일주일간 폐기 비용과 수율 편차를 측정해 14일 체험으로 전환한다.'),sec('13. 개선 계획','1) 제품별 목표 수율 2) 기간별 추세 3) CSV 내보내기 4) 기기 간 동기화 5) 역할별 로그인 6) 변경 이력.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('8/10'),p('폐기와 수율 편차는 반복적인 원가 손실로 이어진다.')],[p('하루 내 완성도'),p('9/10'),p('등록·계산·손실 큐 흐름을 완성했다.')],[p('판매 가능성'),p('8/10'),p('절감 금액으로 가치를 설명하기 쉽다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('8/10'),p('수율과 폐기 비용을 한 큐에서 우선화한다.')],[p('확장 가능성'),p('7/10'),p('추세·내보내기·동기화로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),GREEN),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.2/10','h'),p('생산 손실의 불투명성을 좁은 워크플로로 해결한다. 유료화 전에는 매장이 로컬 단일 기기 방식으로 충분한지, 동기화가 필수인지 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 내부 사용과 고객 인터뷰용 MVP로 사용할 수 있다. 민감정보를 입력하지 말고 실제 사업장 규정을 함께 적용해야 한다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='BatchBalance MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
