from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,PageBreak,Table,TableStyle,Image
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];OUT=R/'report.pdf';SHOT=R/'screenshots/dashboard.png'
pdfmetrics.registerFont(TTFont('D','/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'));pdfmetrics.registerFont(TTFont('DB','/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))
INK=colors.HexColor('#173D37');TEAL=colors.HexColor('#25866F');LINE=colors.HexColor('#DCE5E2');PALE=colors.HexColor('#E7F6EF');MUTED=colors.HexColor('#617572')
s=getSampleStyleSheet();s.add(ParagraphStyle(name='T',fontName='DB',fontSize=28,leading=34,textColor=INK,spaceAfter=10));s.add(ParagraphStyle(name='H',fontName='DB',fontSize=20,leading=25,textColor=INK,spaceAfter=10));s.add(ParagraphStyle(name='S',fontName='DB',fontSize=13,leading=17,textColor=TEAL,spaceBefore=8,spaceAfter=5));s.add(ParagraphStyle(name='B',fontName='D',fontSize=9.5,leading=14.5,textColor=INK,spaceAfter=7));s.add(ParagraphStyle(name='M',fontName='D',fontSize=8,leading=12,textColor=MUTED))
def p(t,st='B'):return Paragraph(t,s[st])
def sec(h,b):return[p(h,'S'),p(b)]
def foot(c,d):c.saveState();c.setStrokeColor(LINE);c.line(20*mm,15*mm,190*mm,15*mm);c.setFont('D',7);c.setFillColor(MUTED);c.drawString(20*mm,10*mm,'ConsignClear · System Foundry · 2026-08-16');c.drawRightString(190*mm,10*mm,f'{d.page} / 6');c.restoreState()
def bullets(xs):return Table([[p('•'),p(x)]for x in xs],colWidths=[5*mm,165*mm],style=[('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),0)])
story=[Spacer(1,8*mm),p('CONSIGNMENT SETTLEMENT CONTROL','S'),p('ConsignClear','T'),p('Pay every maker accurately, right on time.'),Spacer(1,4*mm)]
tbl=Table([[p('Customer','M'),p('Independent select shops, craft stores, and gallery shops')],[p('Problem','M'),p('Sold-item payouts and commission terms are scattered across messages and spreadsheets')],[p('Price','M'),p('KRW 23,000 per store per month')],[p('Status','M'),p('PASS · 10/10 tests · HTTP · workflow · README · security · PDF')]],colWidths=[32*mm,138*mm]);tbl.setStyle(TableStyle([('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('PADDING',(0,0),(-1,-1),8)]));story+=[tbl]+sec('1. Project overview','ConsignClear is a local-first settlement desk for businesses selling goods on behalf of independent makers. It turns each consigned item into a clear stocked, sold, or settled record and calculates the store commission and consignor payout automatically.')+sec('2. Target customer','Independent lifestyle shops, craft stores, museum and gallery shops, and small multi-brand retailers that manage dozens of makers without a dedicated ERP.')+sec('3. Problem','A sale may be recorded at the register while its payout obligation remains in a spreadsheet or message thread. Missed dates damage maker trust; manual commission math creates disputes; and owners cannot see total unpaid liability at a glance.')
story += [PageBreak(),p('Focused workflow','H')]+sec('4. Core features','')+[bullets(['Validated item registration with price, commission rate, consignor, and payout deadline.','Stocked → sold → settled state transitions with guarded actions.','Priority queue for overdue and due-soon payouts, including net payout and store fee totals.'])]+sec('5. How to use','Register a consigned item before shelving it. Mark the item sold when the POS sale is confirmed. Work the settlement queue from overdue to open, then mark the payout settled after payment is recorded.')+sec('6. System structure','Browser forms and dashboard → pure JavaScript validation and settlement engine → localStorage persistence. The calculation engine is isolated from the UI and directly covered by automated tests.')+sec('7. Technology','Semantic HTML, responsive CSS, ES modules, Node.js built-in testing, and Python standard-library HTTP serving. There is no database, external API, account, or paid dependency.')
story += [PageBreak(),p('Running product','H'),p('8. Execution screen','S'),p('The validated demo state contains four items, three sold items, two urgent payouts, and one stocked item. The queue makes payment liability visible before it becomes a maker-relations problem.'),Image(str(SHOT),width=170*mm,height=141.7*mm),p('Actual rendered interface at 1440 × 1200. The red edge identifies the overdue payout.','M')]
story += [PageBreak(),p('Verification','H'),p('9. Test results','S')]
rows=[['Check','Result','Evidence'],['Dependencies','PASS','0 external packages; installation not required'],['Program start','PASS','HTTP 200 using documented command'],['Core workflow','PASS','4 items; payout and fee totals verified'],['Automated tests','PASS','10/10 Node tests'],['README','PASS','Start and test commands executed'],['Secret scan','PASS','No credential pattern found'],['PDF','PASS','6 pages parsed and rendered']]
t=Table([[p(c,'M')for c in r]for r in rows],colWidths=[36*mm,23*mm,111*mm]);t.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),INK),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.4,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('PADDING',(0,0),(-1,-1),7)]));story+=[t]+sec('10. Security and limitations','Inputs have length, range, date-format, identifier, and state validation. Unsafe HTML characters are removed before records reach the UI. Data stays in the browser; there are no credentials, analytics, shell execution, or unauthenticated admin functions. Limitations: this MVP is not an accounting ledger or tax-invoice system, has no receipt attachment, export, authentication, backup, or multi-device collaboration.')
story += [PageBreak(),p('Commercial plan','H')]+sec('11. Price and revenue model','KRW 23,000 per store per month, including unlimited consignors and local records. A KRW 39,000 Plus tier can later add CSV export, payout statements, receipt attachments, and encrypted backup.')+sec('12. First-customer acquisition','')+[bullets(['Pilot with five craft and select shops that currently settle makers in spreadsheets.','Offer free migration of one month of open items and measure hours saved at month-end.','Publish a before/after demo showing an overdue payout surfaced in seconds.','Use maker referrals: makers benefit directly when their retail partners adopt reliable settlement.'])]+sec('13. Improvement plan','Next: editing, filters, CSV export, and printable payout statements. Then: receipt attachments, maker-level summaries, and configurable settlement cycles. Later: optional encrypted sync, role-based review, POS imports, and accounting exports.')+sec('Commercial thesis','The product sells trust and month-end time savings rather than generic inventory management. One avoided payout dispute can justify several months of subscription cost.')
story += [PageBreak(),p('Overall evaluation','H'),p('14. Scorecard','S')]
scores=[('Customer problem strength','9/10','Late or incorrect payouts directly harm supplier relationships.'),('One-day completeness','9/10','The full register-sell-settle loop is implemented.'),('Sale potential','8/10','Clear B2B value in a reachable niche.'),('Maintenance ease','9/10','No backend or paid integration is required.'),('Differentiation','8/10','Maker payout liability is more specific than inventory apps.'),('Expansion potential','9/10','Statements, POS imports, and collaboration extend naturally.')]
q=Table([[p('Dimension','M'),p('Score','M'),p('Reason','M')]]+[[p(a,'M'),p(b,'M'),p(c,'M')]for a,b,c in scores],colWidths=[50*mm,23*mm,97*mm]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),INK),('TEXTCOLOR',(0,0),(-1,0),colors.white),('GRID',(0,0),(-1,-1),.4,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('PADDING',(0,0),(-1,-1),8)]));story+=[q,Spacer(1,10*mm)];box=Table([[p('8.7 / 10','T'),p('<b>Recommendation: proceed to a five-store paid pilot.</b><br/>ConsignClear solves a costly trust problem with a complete, maintainable workflow. Validate POS compatibility and statement format before building cloud accounts.')]],colWidths=[48*mm,122*mm]);box.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),PALE),('BOX',(0,0),(-1,-1),1,TEAL),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('PADDING',(0,0),(-1,-1),12)]));story += [box,Spacer(1,6*mm),p('Final status: PASS — implementation, tests, live start, workflow, README, security scan, screenshot, and PDF rendering verified.','M')]
SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=20*mm,leftMargin=20*mm,topMargin=18*mm,bottomMargin=21*mm,title='ConsignClear MVP Report',author='System Foundry').build(story,onFirstPage=foot,onLaterPages=foot);print(OUT)
