from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
BLUE=HexColor('#205b79');INK=HexColor('#172029');MUTED=HexColor('#66717a');PAPER=HexColor('#f5f3ed');LINE=HexColor('#d5d9da')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=BLUE,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=BLUE,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(BLUE);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'AssetGate · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · BUSINESS MVP','c'),Spacer(1,20),p('AssetGate','t'),Spacer(1,10),p('고객 자료 누락을 착수 전에 발견하는<br/>로컬 우선 인테이크 관리 시스템','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-09-1602-assetgate')],[p('대상 고객'),p('2~10인 웹·디자인·마케팅 제작사')],[p('가격'),p('사업장당 월 ₩19,000')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,BLUE),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','AssetGate는 제작 착수 전에 고객에게 받아야 할 자료의 마감, 수신 상태, 프로젝트 준비도를 한 화면에서 관리하는 업무 도구다.'),sec('2. 대상 고객','고객 자료가 이메일과 메신저에 흩어져 착수 지연을 자주 겪는 소형 웹·디자인·마케팅 제작사와 프리랜서다.'),sec('3. 해결하는 문제','로고·문구·사진·도메인 권한 중 하나만 늦어도 제작 일정 전체가 밀린다. 누락 자료와 잠재 지연일을 먼저 보여 주면 후속 연락의 우선순위를 명확히 할 수 있다.'),sec('4. 핵심 기능','① 검증된 자료 요청 등록 ② 마감 위험도·프로젝트 준비도·잠재 지연 집계 ③ 자료 수신 상태 추적'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 자료 요청과 마감일을 등록하고 위험 큐를 확인한 뒤 도착한 자료를 수신 완료 처리한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·준비도 계산 엔진 → localStorage. 파일 자체나 계정 비밀번호는 저장하지 않는 단일 사업장 구조다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 신규 자료 요청을 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 입력 정제, 범위 검증, 마감 위험, 잠재 지연 합산, 수신 토글, 프로젝트 준비도를 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 길이·범위 제한과 HTML 이스케이프를 적용한다. 실제 비밀번호·API 키 입력을 금지하고 외부 전송은 없다. 파일 업로드, 이메일 발송, 팀 권한은 포함하지 않는다.'),sec('11. 가격과 수익 모델','사업장당 월 ₩19,000 구독. 고객 자료 누락으로 발생하는 일정 손실을 줄이는 가치와 로컬 저장을 판매 포인트로 삼는다.'),sec('12. 첫 고객 확보 방법','웹 제작·디자인 프리랜서 10곳에 무료 인테이크 템플릿을 제공하고, 실제 프로젝트 1건의 착수 준비도를 함께 설정해 14일 체험으로 전환한다.'),sec('13. 개선 계획','1) 요청 링크 공유 2) 이메일 알림 3) 파일 메타데이터 확인 4) 팀 담당자 5) 암호화된 동기화와 감사 이력.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('9/10'),p('자료 누락은 일정과 매출에 직접 영향을 준다.')],[p('하루 내 완성도'),p('9/10'),p('등록·위험 큐·준비도 흐름을 완성했다.')],[p('판매 가능성'),p('8/10'),p('작은 제작사의 반복 업무와 구독 가치가 명확하다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('7/10'),p('자료 수신과 잠재 지연일을 함께 보여 준다.')],[p('확장 가능성'),p('8/10'),p('공유 링크·알림·팀 기능으로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),BLUE),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.4/10','h'),p('고객 자료 누락이라는 강한 업무 문제를 좁은 기능으로 해결한다. 유료화 전에는 이메일 자동화보다 수동 큐만으로도 지불 의사가 있는지 검증해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 소형 제작사의 내부 사용과 고객 인터뷰용 데모로 사용할 수 있다. 실제 자격 증명은 기록하지 않는다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='AssetGate MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
