from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

ROOT=Path(__file__).resolve().parents[1]; OUTPUT=ROOT/"report.pdf"; SCREENSHOT=ROOT/"screenshots/dashboard.png"
INK=colors.HexColor("#211631"); PURPLE=colors.HexColor("#7145E8"); PINK=colors.HexColor("#EC67A1"); PALE=colors.HexColor("#F0EAFF"); MINT=colors.HexColor("#74D7BB"); MUTED=colors.HexColor("#81758B"); LINE=colors.HexColor("#DED5CF")
pdfmetrics.registerFont(TTFont("Body","/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")); pdfmetrics.registerFont(TTFont("BodyBold","/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"))
TITLE=ParagraphStyle("title",fontName="BodyBold",fontSize=31,leading=35,textColor=INK,spaceAfter=8); SUB=ParagraphStyle("sub",fontName="Body",fontSize=11,leading=17,textColor=MUTED,spaceAfter=8); EYE=ParagraphStyle("eye",fontName="BodyBold",fontSize=8,leading=10,textColor=PURPLE,spaceAfter=6); H1=ParagraphStyle("h1",fontName="BodyBold",fontSize=18,leading=22,textColor=INK,spaceAfter=7); H2=ParagraphStyle("h2",fontName="BodyBold",fontSize=12,leading=15,textColor=INK,spaceAfter=4); BODY=ParagraphStyle("body",fontName="Body",fontSize=9.2,leading=14,textColor=colors.HexColor("#4C3E57"),spaceAfter=7); SMALL=ParagraphStyle("small",fontName="Body",fontSize=7.5,leading=10,textColor=MUTED); WHITE=ParagraphStyle("white",fontName="BodyBold",fontSize=9,leading=13,textColor=colors.white)

def frame(canvas,doc):
    canvas.saveState(); w,h=A4; canvas.setFillColor(INK); canvas.rect(0,h-12*mm,w,12*mm,stroke=0,fill=1); canvas.setFillColor(PINK); canvas.setFont("BodyBold",8); canvas.drawString(18*mm,h-7.6*mm,"FILAMENTFAIR / SYSTEM FOUNDRY"); canvas.setFillColor(MUTED); canvas.setFont("Body",7); canvas.drawString(18*mm,10*mm,"2026-08-06 / PERSONAL MVP REPORT"); canvas.drawRightString(w-18*mm,10*mm,str(doc.page)); canvas.restoreState()
def section(n,title,text): return [Paragraph(f"{n:02d} / {title.upper()}",EYE),Paragraph(title,H1),Paragraph(text,BODY)]
def card(title,value,note,accent):
    vs=ParagraphStyle("value",fontName="BodyBold",fontSize=22,leading=27,textColor=INK); t=Table([[Paragraph(title.upper(),SMALL)],[Paragraph(value,vs)],[Paragraph(note,SMALL)]],colWidths=[50*mm]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),colors.white),("BOX",(0,0),(-1,-1),.8,LINE),("LINEABOVE",(0,0),(-1,0),4,accent),("LEFTPADDING",(0,0),(-1,-1),10),("RIGHTPADDING",(0,0),(-1,-1),10),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)])); return t

story=[Spacer(1,10*mm),Paragraph("SYSTEM FOUNDRY / PERSONAL MVP",EYE),Paragraph("FilamentFair",TITLE),Paragraph("A local-first print ledger that prices material, energy, machine time, failure reserve, and margin.",SUB),Spacer(1,12*mm)]
story.append(Table([[card("Product status","PASS","Implemented and verified",PINK),card("Automated tests","8 / 8","Zero failures",MINT),card("One-time price","KRW 12.9K","Personal license",PURPLE)]],colWidths=[55*mm]*3)); story+=[Spacer(1,13*mm)]
story+=section(1,"Project overview","FilamentFair turns slicer estimates into a practical true-cost ledger. A maker enters filament use, print time, power, machine-time cost, failure reserve, and margin to see a cost breakdown and a rounded suggested price.")
story+=section(2,"Target customer","Hobbyist 3D printer owners who make replacement parts, props, prototypes, gifts, or occasional paid requests for friends and local communities.")
story+=section(3,"Problem","Charging only for filament ignores electricity, printer wear, long machine occupation, failed attempts, and a sustainable margin. Makers either lose money or choose an arbitrary price they cannot explain."); story.append(PageBreak())

story += [Paragraph("PRODUCT",EYE),Paragraph("Three focused jobs",TITLE)] + section(4,"Core features","The MVP implements one complete print-costing loop:")
features=[["01",Paragraph("<b>Validated print job intake</b><br/>Capture material, grams, hours, spool price, power, electricity rate, machine cost, reserve, margin, and status.",BODY)],["02",Paragraph("<b>True-cost breakdown</b><br/>Separate material, energy, machine time, and failure reserve instead of hiding them in one guess.",BODY)],["03",Paragraph("<b>Suggested price and job ledger</b><br/>Apply target margin, round to a usable price, and separate planned, completed, and failed work.",BODY)]]
ft=Table(features,colWidths=[14*mm,150*mm]); ft.setStyle(TableStyle([("BACKGROUND",(0,0),(0,-1),INK),("TEXTCOLOR",(0,0),(0,-1),PINK),("FONTNAME",(0,0),(0,-1),"BodyBold"),("ALIGN",(0,0),(0,-1),"CENTER"),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("GRID",(0,0),(-1,-1),.5,LINE),("TOPPADDING",(0,0),(-1,-1),9),("BOTTOMPADDING",(0,0),(-1,-1),9),("LEFTPADDING",(1,0),(1,-1),12)])); story += [ft,Spacer(1,7*mm)]
story+=section(5,"How to use","Copy grams and print hours from the slicer, set the current spool price and printer assumptions, then choose a failure reserve and target margin. Review the breakdown before accepting a request and mark the job completed or failed afterward.")
story+=section(6,"System architecture","A static browser UI calls pure validation and cost functions and stores the job ledger only in localStorage. Node tests exercise the same module. No account, backend, database, analytics, payment system, or external API is used.")
arch=Table([["Browser UI","Cost module","Local storage","Node tests"],["HTML + CSS","Rules + pricing","Device-only data","Pure functions"]],colWidths=[41*mm]*4); arch.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTSIZE",(0,0),(-1,-1),8),("ALIGN",(0,0),(-1,-1),"CENTER"),("GRID",(0,0),(-1,-1),.6,LINE),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8)])); story += [arch,Spacer(1,5*mm)]
story+=section(7,"Technology","Static HTML, responsive CSS, vanilla JavaScript, localStorage, bundled Noto Sans KR fonts, and the built-in Node.js test runner. Runtime dependencies: zero. Paid APIs: zero."); story.append(PageBreak())

story += [Paragraph("VALIDATED INTERFACE",EYE),Paragraph("Actual running screen",TITLE),Paragraph("Captured from headless Chromium after a cosplay clip was validated and priced.",SUB),Spacer(1,4*mm),Image(str(SCREENSHOT),width=160*mm,height=160*mm),Spacer(1,4*mm)]
story+=section(8,"Running screen","The verified screen shows three planned jobs using 535 g, KRW 28,903 estimated cost, and KRW 43,100 suggested price after adding a 95 g cosplay clip. Marking it printed returned planned totals to baseline and increased completed estimated revenue to KRW 11,400."); story.append(PageBreak())

story += [Paragraph("VERIFICATION",EYE),Paragraph("Evidence, not assumptions",TITLE)] + section(9,"Test results","Every required check was executed against the generated project.")
checks=[["Check","Result","Evidence"],["Dependency installation","PASS","npm install completed; zero runtime dependencies"],["Application start","PASS","README HTTP server returned status 200"],["Core workflow","PASS","Planned price KRW 35.3K to 43.1K to 35.3K"],["Automated tests","8 / 8","Validation, breakdown, reserve, price, status"],["README commands","PASS","Install, test, and start commands executed"],["Credential scan","PASS","No secret patterns and no .env file"],["PDF","PASS","Generated, parsed, rendered, visually inspected"]]
tt=Table(checks,colWidths=[48*mm,23*mm,94*mm],repeatRows=1); tt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTNAME",(1,1),(1,-1),"BodyBold"),("TEXTCOLOR",(1,1),(1,-1),PURPLE),("FONTSIZE",(0,0),(-1,-1),7.5),("GRID",(0,0),(-1,-1),.5,LINE),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)])); story += [tt,Spacer(1,8*mm)]
story+=section(10,"Security and limitations","FilamentFair sends no data outside the browser and requires no credentials. Text and numeric inputs are validated, and displayed text is HTML-escaped. Device-local data is unencrypted and disappears when browser storage is cleared. Results depend on user assumptions and exclude tax, delivery, post-processing, design labor, and local business obligations. Users must follow the printer and material manufacturer's safety guidance."); story.append(PageBreak())

story += [Paragraph("GO TO MARKET",EYE),Paragraph("Stop giving machine time away",TITLE)]
story+=section(11,"Pricing and revenue model","Sell a downloadable personal license for KRW 12,900 as a one-time purchase. The price can be recovered by correctly pricing one medium print request. The zero-hosting design keeps operating cost low and supports a simple downloadable product.")
story+=section(12,"First customer acquisition","Recruit twenty hobbyists from Korean 3D printing, model-making, cosplay, and maker communities. Ask them to price three recent jobs with and without machine time and failure reserve. Convert with the visible difference between filament-only and true cost.")
story+=section(13,"Improvement plan","Priorities after observing real costing habits:")
for item in ["Reusable printer and filament presets.","JSON backup and CSV quote export.","Design labor, post-processing, packaging, and delivery options.","Optional currency and tax profiles without payment processing."]: story.append(Paragraph(f"<font color='#7145E8'>●</font> {item}",BODY))
story += [Spacer(1,7*mm),Paragraph("PRODUCT BOUNDARY",H2),Paragraph("FilamentFair should remain a transparent estimating tool. It should not claim to provide tax advice, guarantee profit, control a printer, or replace safe equipment operation and supervision.",BODY)]; story.append(PageBreak())

story += [Paragraph("ASSESSMENT",EYE),Paragraph("Overall evaluation",TITLE)] + section(14,"Overall score","Six dimensions are scored out of 10. A higher maintenance score means easier maintenance.")
ratings=[("Customer problem strength",8,"Underpricing long prints creates immediate, measurable loss."),("One-day completeness",9,"The intake, breakdown, pricing, and status loop is tested."),("Sales potential",8,"One correctly priced request can justify the license."),("Maintenance difficulty",9,"Zero runtime dependencies and no backend keep maintenance light."),("Differentiation",8,"Machine time and failure reserve improve a filament-only calculator."),("Scalability",8,"Presets, exports, labor, delivery, and currencies can expand it.")]
rows=[["Dimension","Score","Rationale"]]+[[n,f"{s}/10",r] for n,s,r in ratings]; rt=Table(rows,colWidths=[52*mm,20*mm,93*mm]); rt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTNAME",(1,1),(1,-1),"BodyBold"),("BACKGROUND",(1,1),(1,-1),PALE),("FONTSIZE",(0,0),(-1,-1),7.4),("GRID",(0,0),(-1,-1),.5,LINE),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8)])); story += [rt,Spacer(1,11*mm)]
big=ParagraphStyle("big",fontName="BodyBold",fontSize=21,leading=25,textColor=PINK); overall=Table([[Paragraph("OVERALL",WHITE),Paragraph("8.3 / 10",big),Paragraph("Proceed to a twenty-maker pricing trial.",WHITE)]],colWidths=[28*mm,48*mm,89*mm]); overall.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),INK),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(-1,-1),12),("RIGHTPADDING",(0,0),(-1,-1),12),("TOPPADDING",(0,0),(-1,-1),14),("BOTTOMPADDING",(0,0),(-1,-1),14)])); story += [overall,Spacer(1,10*mm),Paragraph("Verdict: technically complete and visually polished for a personal MVP. The next useful evidence is whether users change their quoted prices after seeing machine time and failed-print exposure.",BODY)]

doc=SimpleDocTemplate(str(OUTPUT),pagesize=A4,leftMargin=18*mm,rightMargin=18*mm,topMargin=20*mm,bottomMargin=18*mm,title="FilamentFair MVP Report",author="System Foundry",subject="Personal MVP implementation and validation report"); doc.build(story,onFirstPage=frame,onLaterPages=frame); print(f"Generated {OUTPUT}")
