(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.FilamentFair=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  const STATUS=["planned","printed","failed"];
  class ValidationError extends Error{}
  const clean=(value,max,label)=>{const text=String(value??"").trim().replace(/\s+/g," ");if(!text||text.length>max)throw new ValidationError(`${label}을(를) 1~${max}자로 입력하세요.`);return text;};
  const number=(value,min,max,label)=>{const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new ValidationError(`${label} 범위를 확인하세요.`);return n;};
  function normalizeJob(input){if(!STATUS.includes(input.status))throw new ValidationError("작업 상태를 확인하세요.");return{id:clean(input.id,80,"ID"),name:clean(input.name,60,"작업명"),material:clean(input.material,30,"소재"),grams:number(input.grams,1,10000,"사용량"),hours:number(input.hours,.1,1000,"출력시간"),spoolPrice:number(input.spoolPrice,1000,1000000,"필라멘트 가격"),watts:number(input.watts,10,3000,"소비전력"),kwhRate:number(input.kwhRate,1,5000,"전기요금"),machineHourly:number(input.machineHourly,0,100000,"장비시간 비용"),failureRate:number(input.failureRate,0,90,"실패 예비율"),margin:number(input.margin,0,80,"목표 마진"),status:input.status};}
  function estimate(input){const x=normalizeJob(input),materialCost=x.grams*x.spoolPrice/1000,energyCost=x.hours*x.watts/1000*x.kwhRate,machineCost=x.hours*x.machineHourly,baseCost=materialCost+energyCost+machineCost,reserve=baseCost*x.failureRate/100,totalCost=baseCost+reserve,price=Math.ceil((totalCost/(1-x.margin/100))/100)*100;return{...x,materialCost,energyCost,machineCost,reserve,totalCost,price};}
  function buildDashboard(items){const jobs=items.map(estimate),active=jobs.filter(x=>x.status==="planned"),printed=jobs.filter(x=>x.status==="printed"),rank={planned:0,failed:1,printed:2};return{items:jobs.sort((a,b)=>rank[a.status]-rank[b.status]||b.totalCost-a.totalCost),summary:{planned:active.length,plannedGrams:active.reduce((s,x)=>s+x.grams,0),plannedCost:Math.round(active.reduce((s,x)=>s+x.totalCost,0)),plannedPrice:active.reduce((s,x)=>s+x.price,0),printedRevenue:printed.reduce((s,x)=>s+x.price,0)}};}
  function updateStatus(items,id,status){if(!STATUS.includes(status))throw new ValidationError("상태를 확인하세요.");let found=false;const next=items.map(x=>{if(x.id!==id)return x;found=true;return{...x,status};});if(!found)throw new ValidationError("작업을 찾을 수 없습니다.");return next;}
  return{ValidationError,normalizeJob,estimate,buildDashboard,updateStatus};
});
