(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.CareEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const categories=['공기·필터','청소·위생','가전 관리','취미 장비'];const clean=(v,n=80)=>String(v??'').trim().replace(/[<>]/g,'').slice(0,n);const dateOk=v=>/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v+'T00:00:00'));const uid=()=>Math.random().toString(36).slice(2,10);
function addDays(date,days){const d=new Date(date+'T00:00:00Z');d.setUTCDate(d.getUTCDate()+days);return d.toISOString().slice(0,10)}
function normalize(raw){const name=clean(raw.name,40),location=clean(raw.location,30),category=clean(raw.category,20),lastDone=clean(raw.lastDone,10),intervalDays=Number(raw.intervalDays),cost=Number(raw.cost);if(name.length<2)throw Error('관리 항목은 2자 이상 입력하세요.');if(location.length<2)throw Error('위치는 2자 이상 입력하세요.');if(!categories.includes(category))throw Error('지원 카테고리만 선택하세요.');if(!dateOk(lastDone))throw Error('최근 완료일을 확인하세요.');if(!Number.isInteger(intervalDays)||intervalDays<1||intervalDays>730)throw Error('주기는 1~730일이어야 합니다.');if(!Number.isFinite(cost)||cost<0||cost>5000000)throw Error('예상 비용은 0~5,000,000원이어야 합니다.');return{id:clean(raw.id)||uid(),name,location,category,lastDone,intervalDays,cost:Math.round(cost),status:'active'}}
const days=(a,b)=>Math.floor((Date.parse(b+'T00:00:00Z')-Date.parse(a+'T00:00:00Z'))/86400000);
function enrich(item,today){const nextDue=addDays(item.lastDone,item.intervalDays),daysLeft=days(today,nextDue),risk=daysLeft<0?'overdue':daysLeft<=7?'urgent':daysLeft<=30?'soon':'ok';return{...item,nextDue,daysLeft,risk,annualCost:Math.round(item.cost*365/item.intervalDays)}}
function dashboard(items,today){const rows=items.filter(x=>x.status==='active').map(x=>enrich(x,today)).sort((a,b)=>a.daysLeft-b.daysLeft);return{total:rows.length,urgent:rows.filter(x=>['overdue','urgent'].includes(x.risk)).length,annualCost:rows.reduce((s,x)=>s+x.annualCost,0),dueThisMonth:rows.filter(x=>x.daysLeft>=0&&x.daysLeft<=30).length,rows}}
function complete(items,id,today){if(!dateOk(today))throw Error('완료일을 확인하세요.');if(!items.some(x=>x.id===id))throw Error('관리 항목을 찾을 수 없습니다.');return items.map(x=>x.id===id?{...x,lastDone:today}:x)}
return{categories,addDays,normalize,enrich,dashboard,complete};});
