from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, Table, TableStyle, PageBreak, KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

ROOT = Path(__file__).resolve().parents[1]
pdfmetrics.registerFont(TTFont('DV', '/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf'))
pdfmetrics.registerFont(TTFont('DVB', '/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf'))
BLUE, INK, MUTED, PAPER, LINE = map(HexColor, ['#315d72','#212a28','#68746f','#f5f2ec','#d4dad8'])
S = {'t':ParagraphStyle('t',fontName='DVB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='DVB',fontSize=19,leading=26,textColor=BLUE,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='DV',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='DV',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='DVB',fontSize=11,leading=17,textColor=BLUE,alignment=TA_CENTER)}
def p(text, style='b'): return Paragraph(text, S[style])
def sec(title, body): return KeepTogether([p(title,'h'),p(body)])
def frame(canvas, doc):
    canvas.saveState();canvas.setFillColor(PAPER);canvas.rect(0,0,A4[0],A4[1],fill=1,stroke=0);canvas.setFillColor(BLUE);canvas.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);canvas.setFont('DV',7);canvas.setFillColor(MUTED);canvas.drawString(42,24,'MakeupLedger - System Foundry MVP Report');canvas.drawRightString(A4[0]-42,24,str(doc.page));canvas.restoreState()
story=[Spacer(1,90),p('SYSTEM FOUNDRY - BUSINESS MVP','c'),Spacer(1,20),p('MakeupLedger','t'),Spacer(1,10),p('Keep every replacement-session promise visible.','c'),Spacer(1,35)]
cover=Table([[p('Project'),p('2026-08-15-1604-makeupledger')],[p('Customer'),p('Small music, art and language academies')],[p('Price'),p('KRW 21,000 per studio per month')],[p('Status'),p('PASS - automated tests 10/10')]],colWidths=[100,350]);cover.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,BLUE),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));story += [cover,PageBreak()]
story += [sec('1. Project overview','MakeupLedger records replacement-session credits created by absences and cancellations, then prioritizes commitments by expiry date and outstanding value.'),sec('2. Target customer','Small music, art and language academies that run recurring one-to-one or small-group lessons.'),sec('3. Problem','Make-up promises are often scattered across chat messages and notebooks. Missed expiries cause customer disputes, while too many unbooked sessions create an invisible delivery obligation.'),sec('4. Core features','1) Validated credit issue with sessions, expiry and value. 2) Expiry-risk and liability queue. 3) Session redemption and remaining-balance tracking.'),sec('5. Usage','Start the static server, issue a credit whenever a class requires replacement, then use the queue to book urgent learners and redeem one session after delivery.'),PageBreak()]
story += [sec('6. System structure','Browser UI -> validation and expiry/liability engine -> localStorage. No external database, account or paid API is required.'),sec('7. Technology','HTML5, CSS, modern JavaScript modules, Node.js built-in test runner, Python static server and Docker.'),p('8. Running screen','h'),Image(str(ROOT/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('Application state rendered from the verified production calculation engine.','s'),PageBreak()]
story += [sec('9. Test result','Automated tests 10/10 passed. Coverage includes normalization, invalid dates, remaining sessions, liability, day counts, urgent and overdue classification, totals, duplicate references and final redemption. HTTP start, README commands and the calculation workflow were also verified.'),sec('10. Security and limitations','Inputs are length-, range-, date- and status-validated; UI output is escaped. Operators should use non-sensitive learner labels and never enter contact, payment, medical or authentication data. The MVP does not send reminders, book calendars or interpret refund law.'),sec('11. Price and revenue model','KRW 21,000 monthly per studio. The value proposition is fewer disputes, fewer forgotten promises and a clear view of outstanding teaching obligations.'),sec('12. First-customer plan','Offer ten local lesson studios a free one-week migration of their current make-up list. Measure expired credits recovered and admin time saved, then convert useful pilots to a 14-day paid trial.'),sec('13. Improvement plan','1) Calendar booking. 2) Customer reminder links. 3) Policy templates. 4) Teacher assignment. 5) Audit trail and CSV export. 6) Multi-user login.'),PageBreak()]
rows=[[p('Evaluation'),p('Score'),p('Reason')],[p('Problem intensity'),p('9/10'),p('Missed commitments can directly cause refunds and disputes.')],[p('One-day completeness'),p('9/10'),p('Issue, queue, totals and redemption are complete.')],[p('Sales potential'),p('8/10'),p('Studios can compare the fee with prevented refunds.')],[p('Maintenance ease'),p('9/10'),p('Static app with no external service.')],[p('Differentiation'),p('8/10'),p('Expiry risk and obligation value share one queue.')],[p('Expansion potential'),p('8/10'),p('Calendar, reminders and team roles fit naturally.')]]
table=Table(rows,colWidths=[115,55,323]);table.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),BLUE),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));story += [p('14. Overall evaluation','h'),table,Spacer(1,16),p('Overall score 8.5/10','h'),p('A recurring and financially visible operational problem is reduced to a narrow queue. Before paid release, validate reminder and calendar priorities with real studio owners.'),PageBreak(),p('Appendix - verification checklist','h'),p('PASS: zero external dependencies; program start; core workflow; 10 automated tests; README commands; credential scan; PDF parsing and all-page rendering.'),p('Release decision','h'),p('<b>PASS</b> - suitable for local operations and customer interviews. Studio policy and final lesson scheduling remain the operator\'s responsibility.')]
SimpleDocTemplate(str(ROOT/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='MakeupLedger MVP Report',author='System Foundry').build(story,onFirstPage=frame,onLaterPages=frame)
print(ROOT/'report.pdf')
