from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

ROOT=Path(__file__).resolve().parents[1]; OUTPUT=ROOT/"report.pdf"; SCREENSHOT=ROOT/"screenshots/dashboard.png"
INK=colors.HexColor("#142018"); GREEN=colors.HexColor("#216E4A"); LIME=colors.HexColor("#C9EF6A"); PALE=colors.HexColor("#EDF7DF"); ORANGE=colors.HexColor("#FF7B57"); MUTED=colors.HexColor("#748178"); LINE=colors.HexColor("#DED8CA")
pdfmetrics.registerFont(TTFont("Body","/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")); pdfmetrics.registerFont(TTFont("BodyBold","/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"))
TITLE=ParagraphStyle("title",fontName="BodyBold",fontSize=31,leading=35,textColor=INK,spaceAfter=8); SUB=ParagraphStyle("sub",fontName="Body",fontSize=11,leading=17,textColor=MUTED,spaceAfter=8); EYE=ParagraphStyle("eye",fontName="BodyBold",fontSize=8,leading=10,textColor=GREEN,spaceAfter=6); H1=ParagraphStyle("h1",fontName="BodyBold",fontSize=18,leading=22,textColor=INK,spaceAfter=7); H2=ParagraphStyle("h2",fontName="BodyBold",fontSize=12,leading=15,textColor=INK,spaceAfter=4); BODY=ParagraphStyle("body",fontName="Body",fontSize=9.2,leading=14,textColor=colors.HexColor("#35453B"),spaceAfter=7); SMALL=ParagraphStyle("small",fontName="Body",fontSize=7.5,leading=10,textColor=MUTED); WHITE=ParagraphStyle("white",fontName="BodyBold",fontSize=9,leading=13,textColor=colors.white)

def frame(canvas,doc):
    canvas.saveState(); w,h=A4; canvas.setFillColor(INK); canvas.rect(0,h-12*mm,w,12*mm,stroke=0,fill=1); canvas.setFillColor(LIME); canvas.setFont("BodyBold",8); canvas.drawString(18*mm,h-7.6*mm,"RENEWALRADAR / SYSTEM FOUNDRY"); canvas.setFillColor(MUTED); canvas.setFont("Body",7); canvas.drawString(18*mm,10*mm,"2026-08-05 / PERSONAL MVP REPORT"); canvas.drawRightString(w-18*mm,10*mm,str(doc.page)); canvas.restoreState()
def section(n,title,text): return [Paragraph(f"{n:02d} / {title.upper()}",EYE),Paragraph(title,H1),Paragraph(text,BODY)]
def card(title,value,note,accent):
    vs=ParagraphStyle("value",fontName="BodyBold",fontSize=22,leading=27,textColor=INK); t=Table([[Paragraph(title.upper(),SMALL)],[Paragraph(value,vs)],[Paragraph(note,SMALL)]],colWidths=[50*mm]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),colors.white),("BOX",(0,0),(-1,-1),.8,LINE),("LINEABOVE",(0,0),(-1,0),4,accent),("LEFTPADDING",(0,0),(-1,-1),10),("RIGHTPADDING",(0,0),(-1,-1),10),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)])); return t

story=[Spacer(1,10*mm),Paragraph("SYSTEM FOUNDRY / PERSONAL MVP",EYE),Paragraph("RenewalRadar",TITLE),Paragraph("A local-first renewal queue that turns scattered subscriptions into a visible annual cost.",SUB),Spacer(1,12*mm)]
story.append(Table([[card("Product status","PASS","Implemented and verified",LIME),card("Automated tests","8 / 8","Zero failures",ORANGE),card("One-time price","KRW 9.9K","Personal license",GREEN)]],colWidths=[55*mm]*3)); story+=[Spacer(1,13*mm)]
story+=section(1,"Project overview","RenewalRadar lets an individual register recurring digital services, see what will charge within seven days, and compare monthly-equivalent, annual, and canceled-savings totals without connecting a bank account.")
story+=section(2,"Target customer","People paying for several music, creative, cloud, education, or web subscriptions who want a lightweight view of renewal dates and fixed annual spending.")
story+=section(3,"Problem","Small recurring payments are distributed across stores and email receipts. The next charge is easy to miss, while a monthly price hides the annual commitment and makes cancellation decisions harder."); story.append(PageBreak())

story += [Paragraph("PRODUCT",EYE),Paragraph("Three focused jobs",TITLE)] + section(4,"Core features","The MVP implements one complete subscription review loop:")
features=[["01",Paragraph("<b>Validated subscription intake</b><br/>Capture service, category, amount, billing cycle, next renewal, and status with strict limits.",BODY)],["02",Paragraph("<b>Renewal urgency queue</b><br/>Order today's, seven-day, later, paused, and canceled services around the next useful decision.",BODY)],["03",Paragraph("<b>True cost and savings totals</b><br/>Calculate monthly-equivalent and annual cost, then show annual savings from canceled services.",BODY)]]
ft=Table(features,colWidths=[14*mm,150*mm]); ft.setStyle(TableStyle([("BACKGROUND",(0,0),(0,-1),INK),("TEXTCOLOR",(0,0),(0,-1),LIME),("FONTNAME",(0,0),(0,-1),"BodyBold"),("ALIGN",(0,0),(0,-1),"CENTER"),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("GRID",(0,0),(-1,-1),.5,LINE),("TOPPADDING",(0,0),(-1,-1),9),("BOTTOMPADDING",(0,0),(-1,-1),9),("LEFTPADDING",(1,0),(1,-1),12)])); story += [ft,Spacer(1,7*mm)]
story+=section(5,"How to use","Register each active subscription with its next charge date. Review today's and seven-day items before renewal. Change an unused service to canceled so active cost falls and the avoided annual cost remains visible.")
story+=section(6,"System architecture","A static browser UI calls pure validation, urgency, and cost functions and persists state only in localStorage. Node tests exercise the same module. No account, backend, database, analytics, bank access, or external API is used.")
arch=Table([["Browser UI","Tracker module","Local storage","Node tests"],["HTML + CSS","Rules + totals","Device-only data","Pure functions"]],colWidths=[41*mm]*4); arch.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTSIZE",(0,0),(-1,-1),8),("ALIGN",(0,0),(-1,-1),"CENTER"),("GRID",(0,0),(-1,-1),.6,LINE),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8)])); story += [arch,Spacer(1,5*mm)]
story+=section(7,"Technology","Static HTML, responsive CSS, vanilla JavaScript, localStorage, bundled Noto Sans KR fonts, and the built-in Node.js test runner. Runtime dependencies: zero. Paid APIs: zero."); story.append(PageBreak())

story += [Paragraph("VALIDATED INTERFACE",EYE),Paragraph("Actual running screen",TITLE),Paragraph("Captured from headless Chromium after a new audiobook subscription was validated and added.",SUB),Spacer(1,4*mm),Image(str(SCREENSHOT),width=158*mm,height=157*mm),Spacer(1,4*mm)]
story+=section(8,"Running screen","The verified screen shows five active subscriptions, four due within seven days, KRW 38,200 monthly-equivalent cost, and KRW 458,400 annual cost after adding a KRW 7,900 audiobook plan. Canceling that plan returned active totals to baseline and raised canceled annual savings to KRW 201,600."); story.append(PageBreak())

story += [Paragraph("VERIFICATION",EYE),Paragraph("Evidence, not assumptions",TITLE)] + section(9,"Test results","Every required check was executed against the generated project.")
checks=[["Check","Result","Evidence"],["Dependency installation","PASS","npm install completed; zero runtime dependencies"],["Application start","PASS","README HTTP server returned status 200"],["Core workflow","PASS","Active 4 to 5 to 4; savings to KRW 201.6K"],["Automated tests","8 / 8","Validation, cycles, urgency, totals, status"],["README commands","PASS","Install, test, and start commands executed"],["Credential scan","PASS","No secret patterns and no .env file"],["PDF","PASS","Generated, parsed, rendered, visually inspected"]]
tt=Table(checks,colWidths=[48*mm,23*mm,94*mm],repeatRows=1); tt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTNAME",(1,1),(1,-1),"BodyBold"),("TEXTCOLOR",(1,1),(1,-1),GREEN),("FONTSIZE",(0,0),(-1,-1),7.5),("GRID",(0,0),(-1,-1),.5,LINE),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)])); story += [tt,Spacer(1,8*mm)]
story+=section(10,"Security and limitations","RenewalRadar sends no data outside the browser and never asks for account credentials, card numbers, or bank access. Text, amount, cycle, date, and status are validated; displayed text is HTML-escaped. Device-local data is unencrypted and disappears when browser storage is cleared. Renewal dates and prices require manual updates, and the MVP does not send notifications or cancel services automatically."); story.append(PageBreak())

story += [Paragraph("GO TO MARKET",EYE),Paragraph("One avoided renewal pays for it",TITLE)]
story+=section(11,"Pricing and revenue model","Sell a downloadable personal license for KRW 9,900 as a one-time purchase. The price is below many single monthly renewals and the zero-hosting design keeps ongoing cost low. Updates can be included for one major version.")
story+=section(12,"First customer acquisition","Recruit twenty users from Korean personal-finance, productivity, student, and creator communities. Ask each user to enter five subscriptions, complete one renewal review, and report any canceled annual value. Convert with the visible before-and-after annual cost, not a vague budgeting promise.")
story+=section(13,"Improvement plan","Priorities after observing real renewal routines:")
for item in ["JSON backup and restore for device migration.","Calendar export for optional user-controlled reminders.","Price-change history and renewal review notes.","Private encrypted sync only if multi-device demand is proven."]: story.append(Paragraph(f"<font color='#216E4A'>●</font> {item}",BODY))
story += [Spacer(1,7*mm),Paragraph("PRODUCT BOUNDARY",H2),Paragraph("RenewalRadar should remain a lightweight review tool. It should not request banking credentials, cancel services without the user's direct action, or present manually entered costs as verified account balances.",BODY)]; story.append(PageBreak())

story += [Paragraph("ASSESSMENT",EYE),Paragraph("Overall evaluation",TITLE)] + section(14,"Overall score","Six dimensions are scored out of 10. A higher maintenance score means easier maintenance.")
ratings=[("Customer problem strength",8,"Unnoticed renewals create recurring and measurable personal cost."),("One-day completeness",9,"The register, prioritize, total, and cancel loop is browser-tested."),("Sales potential",8,"One avoided renewal can clearly justify the one-time price."),("Maintenance difficulty",9,"Zero runtime dependencies and no backend keep maintenance light."),("Differentiation",7,"Annual savings visibility helps, though subscription trackers exist."),("Scalability",8,"Backups, calendar export, history, and sync offer expansion paths.")]
rows=[["Dimension","Score","Rationale"]]+[[n,f"{s}/10",r] for n,s,r in ratings]; rt=Table(rows,colWidths=[52*mm,20*mm,93*mm]); rt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTNAME",(1,1),(1,-1),"BodyBold"),("BACKGROUND",(1,1),(1,-1),PALE),("FONTSIZE",(0,0),(-1,-1),7.4),("GRID",(0,0),(-1,-1),.5,LINE),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8)])); story += [rt,Spacer(1,11*mm)]
big=ParagraphStyle("big",fontName="BodyBold",fontSize=21,leading=25,textColor=LIME); overall=Table([[Paragraph("OVERALL",WHITE),Paragraph("8.2 / 10",big),Paragraph("Proceed to a twenty-user renewal review trial.",WHITE)]],colWidths=[28*mm,48*mm,89*mm]); overall.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),INK),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(-1,-1),12),("RIGHTPADDING",(0,0),(-1,-1),12),("TOPPADDING",(0,0),(-1,-1),14),("BOTTOMPADDING",(0,0),(-1,-1),14)])); story += [overall,Spacer(1,10*mm),Paragraph("Verdict: technically complete and visually polished for a personal MVP. The next useful evidence is whether users return before renewal dates and record enough avoided cost to justify purchase.",BODY)]

doc=SimpleDocTemplate(str(OUTPUT),pagesize=A4,leftMargin=18*mm,rightMargin=18*mm,topMargin=20*mm,bottomMargin=18*mm,title="RenewalRadar MVP Report",author="System Foundry",subject="Personal MVP implementation and validation report"); doc.build(story,onFirstPage=frame,onLaterPages=frame); print(f"Generated {OUTPUT}")
