from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
V=HexColor('#5a45a6');INK=HexColor('#1b2028');MUTED=HexColor('#6d6878');PAPER=HexColor('#f5f3ee');LINE=HexColor('#d8d6dd')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=V,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=V,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(V);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'PortPilot · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · PERSONAL MVP','c'),Spacer(1,20),p('PortPilot','t'),Spacer(1,10),p('기기와 충전기의 포트·출력을 비교해<br/>여행 짐을 줄이는 로컬 우선 도구','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-10-0905-portpilot')],[p('대상 고객'),p('여러 디지털 기기와 충전기를 보유한 개인')],[p('가격'),p('1회 ₩9,900')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,V),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','PortPilot은 기기와 충전기의 포트·정격 출력을 비교하고, 선택한 여행 기기를 충전할 최소 구성안을 제시하는 브라우저 기반 개인 도구다.'),sec('2. 대상 고객','노트북, 휴대폰, 보조배터리, 휴대용 모니터 등 여러 디지털 기기와 충전기를 보유한 학생·여행자·메이커다.'),sec('3. 해결하는 문제','포트가 같아도 출력이 부족하면 충전이 느리거나 불가능하다. 외출 때 충전기를 과하게 챙기거나 필요한 규격을 빠뜨리는 문제를 호환성 표와 구성 추천으로 줄인다.'),sec('4. 핵심 기능','① 검증된 기기·충전기 등록 ② 포트·출력 기반 호환성 분석 ③ 여행 기기 선택과 최소 충전기 구성 추천'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 장비의 포트와 정격 출력을 등록하고 여행 포함 기기를 선택한 뒤 추천 구성을 확인한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·호환성·그리디 구성 엔진 → localStorage. 계정이나 외부 데이터 전송이 없는 단일 사용자 구조다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 여행용 기기를 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 입력 정제와 범위 검증, 포트·출력 호환성, 미지원 기기 집계, 여행 선택 토글을 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 길이·출력 범위 제한과 HTML 이스케이프를 적용한다. 비밀값과 외부 전송은 없다. USB 전력 협상, 케이블 정격, 다중 포트 동시 출력은 자동 판별하지 않는다.'),sec('11. 가격과 수익 모델','1회 ₩9,900 라이선스. 다양한 충전 장비를 가진 사용자가 구매 중복과 여행 짐을 줄이는 가치를 판매 포인트로 삼는다.'),sec('12. 첫 고객 확보 방법','노트북·모바일·메이커 커뮤니티에 무료 충전 규격 체크리스트를 배포하고, 장비 5개 이상 사용자를 유료 버전으로 전환한다.'),sec('13. 개선 계획','1) 케이블 등록 2) 다중 포트 동시 출력 3) JSON 백업 4) 제조사 규격 템플릿 5) 여행 프로필 저장.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('8/10'),p('충전기 중복 구매와 누락이 반복된다.')],[p('하루 내 완성도'),p('9/10'),p('등록·호환성·추천 흐름을 완성했다.')],[p('판매 가능성'),p('7/10'),p('다기기 사용자에게 저가 구매 가치가 있다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('8/10'),p('보유 장비 기반 여행 구성까지 계산한다.')],[p('확장 가능성'),p('8/10'),p('케이블·동시 출력·제품 DB로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),V),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.1/10','h'),p('사용자의 실제 장비 목록을 바탕으로 호환성과 여행 구성을 함께 보여 주는 실용적인 개인 MVP다. 판매 전에는 다중 포트 동시 출력 계산 수요를 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 개인 로컬 사용과 고객 인터뷰용 데모로 사용할 수 있다. 실제 사용 전 제조사 정격과 케이블 사양을 확인해야 한다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='PortPilot MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
