from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'));G=HexColor('#245c44');I=HexColor('#1d2520');M=HexColor('#68736c');P=HexColor('#f2efe7');L=HexColor('#d9d5ca')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=I),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=G,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=I,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=M),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=G,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(P);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(G);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(M);c.drawString(42,24,'RestockRun · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · BUSINESS MVP','c'),Spacer(1,20),p('RestockRun','t'),Spacer(1,10),p('소모품 품절 위험과 재주문 예산을<br/>한 화면에서 관리하는 운영 보드','c'),Spacer(1,35)];t=Table([[p('프로젝트'),p('2026-08-08-1604-restockrun')],[p('대상 고객'),p('소형 인쇄·3D 프린팅·사진 스튜디오')],[p('가격'),p('사업장당 월 ₩16,000')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,G),('INNERGRID',(0,0),(-1,-1),.5,L),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','RestockRun은 현재 수량과 일평균 사용량으로 재고 런웨이를 계산하고, 재주문 순서와 예산을 제안하는 브라우저 기반 업무 도구다.'),sec('2. 대상 고객','잉크, 용지, 필라멘트, 포장재, 촬영 소모품을 반복 사용하는 1~10인 스튜디오와 출력소다.'),sec('3. 해결하는 문제','소모품 수량과 사용 속도를 따로 관리하면 작업 중 품절로 납기가 지연되고 급한 소량 구매로 원가가 높아진다.'),sec('4. 핵심 기능','① 검증된 소모품 등록 ② 사용 가능 일수 기반 품절 위험 큐와 권장 주문 예산 ③ 한 번의 사용 기록으로 재고 즉시 차감'),sec('5. 사용 방법','npm install, npm test, npm start로 실행한다. 소모품을 등록하고 품절 위험 큐를 확인한 뒤 사용 버튼으로 실제 재고를 반영한다.'),PageBreak(),sec('6. 시스템 구조','브라우저 UI → 입력 검증·런웨이 계산 엔진 → localStorage. 서버나 공급사 API 없이 단일 기기에서 동작한다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 테스트 러너, Python 정적 서버, Docker. 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 새 소모품을 등록한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 입력 검증, 음수·0 차단, 런웨이와 권장 주문 계산, 큐 정렬, 재고 차감을 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 범위와 허용 카테고리를 제한하고 HTML을 이스케이프한다. 비밀값과 외부 전송은 없다. 다중 사용자, 발주 승인, 공급사 연동은 제공하지 않는다.'),sec('11. 가격과 수익 모델','사업장당 월 ₩16,000 구독. 품절 방지와 긴급 구매 감소로 절감된 비용을 가치 기준으로 제시한다.'),sec('12. 첫 고객 확보 방법','지역 출력소와 메이커 스튜디오 10곳에 7일 체험을 제공하고, 품절 위험 품목과 다음 주문 예산 리포트로 전환을 유도한다.'),sec('13. 개선 계획','1) CSV 가져오기 2) 재고 조정 이력 3) 공급사별 가격 비교 4) 승인 워크플로 5) 다중 사용자와 지점 권한.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('8/10'),p('품절은 납기 지연과 긴급 구매 비용으로 직결된다.')],[p('하루 내 완성도'),p('9/10'),p('등록·계산·사용 반영 흐름을 완성했다.')],[p('판매 가능성'),p('8/10'),p('비용 절감 효과를 수치로 보여 주기 쉽다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('7/10'),p('단순 수량 대신 일평균 사용량으로 런웨이를 계산한다.')],[p('확장 가능성'),p('8/10'),p('발주·공급사·다지점 기능으로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),G),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,L),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.2/10','h'),p('작은 사업장의 반복적인 품절 문제를 단순한 입력만으로 줄일 수 있다. 실제 판매 전에는 업종별 사용 단위와 주문 주기를 인터뷰로 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 단일 사업장 로컬 운영과 고객 인터뷰용 데모로 사용할 수 있다. 자동 발주 전에는 승인과 공급사 검증 기능이 필요하다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='RestockRun MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf);print(R/'report.pdf')
