from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
VIOLET=HexColor('#5b43a6');INK=HexColor('#20243a');MUTED=HexColor('#686b7d');PAPER=HexColor('#f7f5f0');LINE=HexColor('#d9d6e2')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=VIOLET,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=VIOLET,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(VIOLET);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'FocusQueue · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · PERSONAL MVP','c'),Spacer(1,20),p('FocusQueue','t'),Spacer(1,10),p('마감과 예상 시간을 계산해<br/>오늘 먼저 끝낼 공부를 정하는 개인 도구','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-11-0906-focusqueue')],[p('대상 고객'),p('학생 및 개인 학습자')],[p('가격'),p('1회 ₩7,900')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,VIOLET),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','FocusQueue는 마감일, 중요도, 예상 학습시간을 점수화해 우선순위를 보여 주고, 오늘 가능한 시간 안에서 실행 가능한 계획을 구성하는 브라우저 도구다.'),sec('2. 대상 고객','과제와 시험 준비를 동시에 관리하는 학생, 대학생, 자격시험 학습자처럼 할 일은 많지만 오늘 무엇부터 시작할지 정하기 어려운 개인이다.'),sec('3. 해결하는 문제','일반 체크리스트는 모든 항목을 평평하게 보여 줘 마감 임박 과제와 큰 과제를 놓치기 쉽다. 제한된 시간에 맞는 구체적인 시작 순서가 필요하다.'),sec('4. 핵심 기능','① 검증된 학습 할 일 등록 ② 마감·중요도 기반 우선순위 큐 ③ 오늘 시간 예산에 맞춘 자동 계획'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 과목·할 일·마감·예상시간·중요도를 등록하고, 오늘 가능한 시간을 조정한 뒤 강조된 항목부터 완료한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·우선순위·시간 예산 계산 엔진 → localStorage. 계정, 서버, 외부 데이터 전송이 없는 단일 사용자 구조다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 신규 학습 할 일을 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 입력 정제, 시간·중요도 범위, 마감 긴급도, 점수 비교, 시간 예산 계획, 남은 시간 합산, 완료 토글을 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 길이·숫자 범위 제한과 HTML 이스케이프를 적용한다. 비밀값과 외부 전송은 없다. 우선순위는 참고용이며 휴식, 학교 일정, 실제 난이도를 대신 판단하지 않는다.'),sec('11. 가격과 수익 모델','1회 ₩7,900 구매. 광고나 계정 없이 기기 안에서 바로 쓰는 가벼운 학습 계획 도구로 판매하고, 향후 선택형 동기화 기능만 별도 제공한다.'),sec('12. 첫 고객 확보 방법','학생 커뮤니티와 스터디 그룹에 무료 주간 학습 템플릿을 배포하고, 20명에게 일주일간 사용 인터뷰를 진행해 구매 전환 메시지를 검증한다.'),sec('13. 개선 계획','1) 반복 일정 2) 과목별 통계 3) JSON 백업 4) 선택형 알림 5) 접근성 설정. 무리한 학습을 유도하지 않도록 휴식 안내도 강화한다.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('8/10'),p('무엇부터 시작할지 결정하는 부담이 반복된다.')],[p('하루 내 완성도'),p('9/10'),p('등록·점수·시간 계획·완료 흐름을 완성했다.')],[p('판매 가능성'),p('8/10'),p('저렴한 1회 구매와 로컬 저장이 명확하다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('8/10'),p('우선순위와 실제 시간 예산을 함께 계산한다.')],[p('확장 가능성'),p('7/10'),p('반복 일정·백업·통계로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),VIOLET),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.2/10','h'),p('결정 부담이라는 흔한 문제를 시간 예산까지 포함한 좁은 흐름으로 해결한다. 유료화 전에는 학생이 실제로 매일 입력을 유지하는지 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 개인 사용과 고객 인터뷰용 MVP로 사용할 수 있다. 점수는 참고이며 충분한 휴식과 실제 일정을 함께 고려해야 한다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='FocusQueue MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
