const E=window.SlotEngine,TODAY='2026-08-07',CK='slotsignal.customers.v1',SK='slotsignal.slots.v1';
const customerSeed=[{id:'c1',name:'김하늘',service:'컷',availability:'afternoon',joined:'2026-07-28',status:'waiting'},{id:'c2',name:'박서준',service:'컬러',availability:'evening',joined:'2026-07-30',status:'waiting'},{id:'c3',name:'이도윤',service:'컷',availability:'evening',joined:'2026-08-02',status:'waiting'},{id:'c4',name:'최유진',service:'클리닉',availability:'morning',joined:'2026-08-01',status:'waiting'}];
const slotSeed=[{id:'s1',service:'컷',date:'2026-08-08',time:'15:30',price:28000,status:'open'},{id:'s2',service:'컬러',date:'2026-08-08',time:'18:30',price:89000,status:'open'},{id:'s3',service:'클리닉',date:'2026-08-09',time:'10:00',price:65000,status:'open'}];
let customers=load(CK,customerSeed),slots=load(SK,slotSeed);const $=id=>document.getElementById(id),won=n=>`₩${n.toLocaleString('ko-KR')}`;const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function load(k,fallback){try{return JSON.parse(localStorage.getItem(k))||fallback}catch{return fallback}}function save(){localStorage.setItem(CK,JSON.stringify(customers));localStorage.setItem(SK,JSON.stringify(slots))}
function render(){const d=E.dashboard(customers,slots,TODAY);$('waitingCount').textContent=d.waitingCount;$('openCount').textContent=d.openCount;$('revenueAtRisk').textContent=won(d.revenueAtRisk);$('heroPriority').textContent=`${d.queue.filter(x=>x.matchScore>=90).length}명`;$('todayLabel').textContent='기준일 2026.08.07';$('queue').innerHTML=d.queue.length?d.queue.map((x,i)=>`<article class="match"><div class="rank">${i+1}</div><div><span class="badge ${x.matchScore>=90?'high':'normal'}">적합도 ${x.matchScore}</span><h3>${esc(x.name)} · ${esc(x.slotService)}</h3><p>${x.slotDate} ${x.slotTime} · ${x.periodMatch?'시간대 일치':'시간 확인 필요'} · 대기 ${E.score(x,{service:x.slotService,time:x.slotTime,date:x.slotDate,status:'open'},TODAY)-40-(x.periodMatch?35:0)-Math.max(0,20-Math.min(20,Math.floor((Date.parse(x.slotDate)-Date.parse(TODAY))/86400000)))}일</p></div><div class="money"><b>${won(x.slotPrice)}</b><small>회수 가능 매출</small></div><button data-slot="${esc(x.slotId)}" data-customer="${esc(x.id)}">예약 확정</button></article>`).join(''):'<div class="empty">현재 연락할 대기 고객이 없습니다.</div>'}
$('customerForm').joined.value=TODAY;$('slotForm').date.value='2026-08-09';$('slotForm').time.value='14:00';
$('customerForm').addEventListener('submit',e=>{e.preventDefault();$('message').textContent='';try{customers=[...customers,E.normalizeCustomer(Object.fromEntries(new FormData(e.currentTarget)))];save();e.currentTarget.reset();e.currentTarget.joined.value=TODAY;render();$('message').textContent='대기 고객을 등록했습니다.'}catch(err){$('message').textContent=err.message}});
$('slotForm').addEventListener('submit',e=>{e.preventDefault();$('slotMessage').textContent='';try{slots=[...slots,E.normalizeSlot(Object.fromEntries(new FormData(e.currentTarget)))];save();e.currentTarget.reset();e.currentTarget.date.value='2026-08-09';e.currentTarget.time.value='14:00';render();$('slotMessage').textContent='빈 슬롯을 등록했습니다.'}catch(err){$('slotMessage').textContent=err.message}});
$('queue').addEventListener('click',e=>{const slotId=e.target.dataset.slot,customerId=e.target.dataset.customer;if(!slotId)return;const next=E.fillSlot(customers,slots,slotId,customerId);customers=next.customers;slots=next.slots;save();render()});render();
