from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
GREEN=HexColor('#24735d');INK=HexColor('#202b27');MUTED=HexColor('#65736d');PAPER=HexColor('#f6f4ef');LINE=HexColor('#d4dcd8')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=GREEN,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=GREEN,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(GREEN);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'ShiftSeal · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · BUSINESS MVP','c'),Spacer(1,20),p('ShiftSeal','t'),Spacer(1,10),p('교대 인수인계 누락과 미해결 업무를<br/>마감 전에 봉인하는 로컬 우선 시스템','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-11-1600-shiftseal')],[p('대상 고객'),p('소형 카페·소매점·예약형 매장')],[p('가격'),p('사업장당 월 ₩15,000')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,GREEN),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','ShiftSeal은 교대 전 전달해야 할 업무를 구역·담당자·완료시각·중요도로 등록하고, 시간 위험과 완료율을 계산하는 브라우저 기반 업무 시스템이다.'),sec('2. 대상 고객','2~15인이 교대로 근무하는 소형 카페, 소매점, 예약형 클래스처럼 구두 전달과 메신저에 인수인계를 의존하는 사업장이다.'),sec('3. 해결하는 문제','바쁜 교대 시간에는 미완료 업무가 대화 속에서 사라진다. 담당자와 마감 시각이 명확한 큐를 만들면 다음 근무자가 우선 처리할 일을 즉시 알 수 있다.'),sec('4. 핵심 기능','① 검증된 인계 항목 등록 ② 시간·중요도 기반 우선순위 큐 ③ 미완료 수와 교대 완료율 대시보드'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 교대 전에 업무를 등록하고 시간 초과·긴급 항목부터 확인한 뒤 처리한 항목을 완료한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·시간 위험·완료율 계산 엔진 → localStorage. 외부 전송과 관리자 화면이 없는 단일 사업장 구조다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 신규 인계 항목을 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 입력 정제, 시간·중요도 검증, 긴급·기한초과 판정, 점수 비교, 완료율, 상태 전환을 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 길이·숫자 범위 제한과 HTML 이스케이프를 적용한다. 고객 개인정보·비밀번호·결제정보를 입력하지 않도록 안내한다. 다중 사용자 동기화와 감사 로그는 포함하지 않는다.'),sec('11. 가격과 수익 모델','사업장당 월 ₩15,000 구독. 교대 누락으로 생기는 재작업과 고객 응대 지연을 줄이는 가치를 판매 포인트로 삼는다.'),sec('12. 첫 고객 확보 방법','동네 카페와 예약형 매장 10곳에 무료 교대 체크리스트를 제공하고, 일주일간 누락 건수와 인계 시간을 측정해 14일 체험으로 전환한다.'),sec('13. 개선 계획','1) 교대 템플릿 2) 반복 업무 3) 기기 간 동기화 4) 역할별 로그인 5) 변경 이력 6) 선택형 알림.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('8/10'),p('인계 누락은 재작업과 고객 응대 지연을 만든다.')],[p('하루 내 완성도'),p('9/10'),p('등록·위험 큐·완료율 흐름을 완성했다.')],[p('판매 가능성'),p('8/10'),p('교대 사업장의 반복 문제와 가격이 명확하다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('8/10'),p('완료 시각과 인계 완료율을 함께 관리한다.')],[p('확장 가능성'),p('8/10'),p('템플릿·동기화·감사 로그로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),GREEN),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.3/10','h'),p('구두 인수인계의 누락을 좁은 워크플로로 해결한다. 유료화 전에는 매장이 로컬 단일 기기 방식으로 충분한지, 동기화가 필수인지 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 내부 사용과 고객 인터뷰용 MVP로 사용할 수 있다. 민감정보를 입력하지 말고 실제 사업장 규정을 함께 적용해야 한다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='ShiftSeal MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
