const test=require('node:test'),assert=require('node:assert/strict'),E=require('../app/engine.js'),today='2026-08-08';
test('month addition preserves valid month end',()=>assert.equal(E.addMonths('2025-01-31',1),'2025-02-28'));
test('valid purchase is normalized',()=>{const x=E.normalize({name:'무선 이어폰',store:'공식몰',category:'전자기기',purchaseDate:'2025-08-08',warrantyMonths:'12',price:'249000',hasReceipt:'on'});assert.equal(x.price,249000);assert.equal(x.hasReceipt,true)});
test('invalid name and category are rejected',()=>{assert.throws(()=>E.normalize({name:'A',store:'공식몰',category:'전자기기',purchaseDate:today,warrantyMonths:12,price:10000}),/2자/);assert.throws(()=>E.normalize({name:'제품명',store:'공식몰',category:'식품',purchaseDate:today,warrantyMonths:12,price:10000}),/카테고리/)});
test('warranty duration and price are bounded',()=>{assert.throws(()=>E.normalize({name:'제품명',store:'공식몰',category:'가전',purchaseDate:today,warrantyMonths:121,price:10000}),/1~120/);assert.throws(()=>E.normalize({name:'제품명',store:'공식몰',category:'가전',purchaseDate:today,warrantyMonths:12,price:10}),/1,000/)});
test('risk becomes urgent within thirty days',()=>{const x=E.enrich({purchaseDate:'2025-08-25',warrantyMonths:12,hasReceipt:true,hasSerial:false},today);assert.equal(x.risk,'urgent');assert.equal(x.ready,1)});
test('expired item is detected',()=>assert.equal(E.enrich({purchaseDate:'2024-01-01',warrantyMonths:12,hasReceipt:true,hasSerial:true},today).risk,'expired'));
test('dashboard sorts by expiry and sums active value',()=>{const items=[{id:'a',purchaseDate:'2026-01-01',warrantyMonths:12,price:10000,hasReceipt:true,hasSerial:true,status:'active'},{id:'b',purchaseDate:'2025-08-01',warrantyMonths:12,price:20000,hasReceipt:false,hasSerial:false,status:'active'}],d=E.dashboard(items,today);assert.equal(d.rows[0].id,'b');assert.equal(d.protectedValue,10000);assert.equal(d.missingProof,1)});
test('proof toggle only changes allowed field',()=>{const x=[{id:'a',hasReceipt:false,hasSerial:false}],r=E.toggleProof(x,'a','hasReceipt');assert.equal(r[0].hasReceipt,true);assert.throws(()=>E.toggleProof(x,'a','price'),/허용되지/)});
