const Engine=window.QuoteLoop;const STORAGE_KEY="quoteloop.v1";const today="2026-08-04";const statusLabels={draft:"작성 중",sent:"발송",followup:"후속 연락",won:"성사",lost:"보류·실패"};
const defaults={quotes:[
{id:"q-1",clientAlias:"브랜드 A",service:"브랜드 촬영 패키지",amount:1800000,probability:70,status:"followup",followUpOn:"2026-08-03",sentOn:"2026-07-29"},
{id:"q-2",clientAlias:"오피스 B",service:"정기 청소 3개월",amount:960000,probability:50,status:"sent",followUpOn:"2026-08-04",sentOn:"2026-08-01"},
{id:"q-3",clientAlias:"메이커 C",service:"제품 랜딩페이지",amount:2400000,probability:70,status:"followup",followUpOn:"2026-08-06",sentOn:"2026-07-31"},
{id:"q-4",clientAlias:"행사 D",service:"행사 영상 제작",amount:1200000,probability:90,status:"won",followUpOn:"2026-08-02",sentOn:"2026-07-26"},
{id:"q-5",clientAlias:"카페 E",service:"메뉴 디자인",amount:650000,probability:20,status:"lost",followUpOn:"2026-08-01",sentOn:"2026-07-25"}]};
let state=load();function load(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY));if(data&&Array.isArray(data.quotes))return data;}catch(_){}return structuredClone(defaults);}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));}const money=value=>`₩${Number(value).toLocaleString("ko-KR")}`;const escapeHtml=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
function render(){const result=Engine.buildDashboard(state.quotes,today);const s=result.summary;document.querySelector("#open-count").textContent=s.openQuotes;document.querySelector("#overdue-count").textContent=s.overdue;document.querySelector("#open-value").textContent=money(s.openValue);document.querySelector("#weighted-value").textContent=money(s.weightedPipeline);document.querySelector("#won-value").textContent=`성사 누계 ${money(s.wonRevenue)}`;document.querySelector("#quote-list").innerHTML=result.items.map(q=>`<article class="quote-card ${q.urgency.key}"><div class="urgency"><span>${q.urgency.label}</span><small>${statusLabels[q.status]}</small></div><div class="quote-copy"><div class="meta"><span>${q.clientAlias}</span><span>후속 ${q.followUpOn}</span></div><h3>${escapeHtml(q.service)}</h3><p>성사 가능성 ${q.probability}% · 발송일 ${q.sentOn}</p></div><div class="quote-value"><span>견적 금액</span><b>${money(q.amount)}</b></div><form class="status-form" data-id="${q.id}"><select name="status">${Object.entries(statusLabels).map(([v,l])=>`<option value="${v}" ${q.status===v?"selected":""}>${l}</option>`).join("")}</select><button>저장</button></form></article>`).join("");}
document.querySelector("#quote-form").addEventListener("submit",event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));try{state.quotes.push(Engine.normalizeQuote({...values,id:`q-${Date.now()}`,sentOn:today}));save();event.currentTarget.reset();document.querySelector("#follow-date").value="2026-08-05";document.querySelector("#notice").textContent="견적을 등록하고 후속 연락 큐를 갱신했습니다.";document.querySelector("#form-message").textContent="";render();}catch(error){document.querySelector("#form-message").textContent=error.message;}});
document.querySelector("#quote-list").addEventListener("submit",event=>{const form=event.target.closest(".status-form");if(!form)return;event.preventDefault();try{state.quotes=Engine.updateStatus(state.quotes,form.dataset.id,new FormData(form).get("status"));save();document.querySelector("#notice").textContent="견적 상태를 갱신했습니다.";render();}catch(error){document.querySelector("#notice").textContent=error.message;}});
document.querySelector("#reset").addEventListener("click",()=>{state=structuredClone(defaults);save();document.querySelector("#notice").textContent="샘플 데이터를 복원했습니다.";render();});document.querySelector("#follow-date").value="2026-08-05";render();
