(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.QuoteLoop=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  class ValidationError extends Error{}
  const statuses=new Set(["draft","sent","followup","won","lost"]);
  const probabilities=new Set([20,50,70,90]);
  function text(value,label,max){const result=String(value??"").trim().replace(/\s+/g," ");if(!result||result.length>max)throw new ValidationError(`${label}은 1~${max}자로 입력하세요.`);return result;}
  function money(value){const number=Number(value);if(!Number.isInteger(number)||number<10000||number>1000000000)throw new ValidationError("견적 금액은 1만원~10억원의 정수로 입력하세요.");return number;}
  function validDate(value,label){const date=String(value??"");if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||Number.isNaN(Date.parse(`${date}T00:00:00Z`)))throw new ValidationError(`${label}을 확인하세요.`);return date;}
  function normalizeQuote(input){const status=String(input.status??"");if(!statuses.has(status))throw new ValidationError("견적 상태를 확인하세요.");const probability=Number(input.probability);if(!probabilities.has(probability))throw new ValidationError("성사 가능성을 확인하세요.");return{id:text(input.id,"견적 ID",80),clientAlias:text(input.clientAlias,"고객 별칭",40),service:text(input.service,"서비스명",70),amount:money(input.amount),probability,status,followUpOn:validDate(input.followUpOn,"후속 연락일"),sentOn:validDate(input.sentOn||input.followUpOn,"견적 발송일")};}
  function daysBetween(today,date){return Math.round((Date.parse(`${date}T00:00:00Z`)-Date.parse(`${today}T00:00:00Z`))/86400000);}
  function classify(days,status){if(status==="won"||status==="lost")return{key:"closed",label:"종료",rank:4};if(days<0)return{key:"overdue",label:`${Math.abs(days)}일 지연`,rank:0};if(days===0)return{key:"today",label:"오늘 연락",rank:1};if(days<=3)return{key:"soon",label:`${days}일 남음`,rank:2};return{key:"later",label:`${days}일 남음`,rank:3};}
  function buildDashboard(quotes,today){validDate(today,"기준일");const items=quotes.map(normalizeQuote).map(quote=>{const daysUntilFollowUp=daysBetween(today,quote.followUpOn);return{...quote,daysUntilFollowUp,urgency:classify(daysUntilFollowUp,quote.status)};}).sort((a,b)=>a.urgency.rank-b.urgency.rank||a.daysUntilFollowUp-b.daysUntilFollowUp||b.amount-a.amount);const open=items.filter(item=>!['won','lost'].includes(item.status));return{items,summary:{openQuotes:open.length,overdue:open.filter(item=>item.daysUntilFollowUp<0).length,openValue:open.reduce((sum,item)=>sum+item.amount,0),weightedPipeline:open.reduce((sum,item)=>sum+Math.round(item.amount*item.probability/100),0),wonRevenue:items.filter(item=>item.status==='won').reduce((sum,item)=>sum+item.amount,0)}};}
  function updateStatus(quotes,id,status){if(!statuses.has(status))throw new ValidationError("견적 상태를 확인하세요.");let found=false;const result=quotes.map(quote=>{if(quote.id!==id)return quote;found=true;return{...quote,status};});if(!found)throw new ValidationError("견적을 찾을 수 없습니다.");return result;}
  return{ValidationError,normalizeQuote,buildDashboard,updateStatus};
});
