from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet,ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,PageBreak,Table,TableStyle,Image,KeepTogether
ROOT=Path(__file__).resolve().parents[1];OUT=ROOT/'report.pdf';pdfmetrics.registerFont(TTFont('Snap',ROOT/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('SnapB',ROOT/'app/fonts/noto-sans-kr-bold.ttf'))
INK=colors.HexColor('#172b3a');BLUE=colors.HexColor('#176b87');SKY=colors.HexColor('#dff5f7');CREAM=colors.HexColor('#fff9ed');CORAL=colors.HexColor('#ff765f');MUTED=colors.HexColor('#60717a')
title=ParagraphStyle('t',fontName='SnapB',fontSize=29,leading=36,textColor=INK,spaceAfter=12);h1=ParagraphStyle('h1',fontName='SnapB',fontSize=20,leading=25,textColor=INK,spaceBefore=5,spaceAfter=10);h2=ParagraphStyle('h2',fontName='SnapB',fontSize=12,leading=17,textColor=BLUE,spaceBefore=9,spaceAfter=5);body=ParagraphStyle('b',fontName='Snap',fontSize=9.5,leading=15,textColor=INK,spaceAfter=7);small=ParagraphStyle('s',fontName='Snap',fontSize=8,leading=12,textColor=MUTED);center=ParagraphStyle('c',parent=body,alignment=TA_CENTER)
def P(x,s=body):return Paragraph(x,s)
def section(n,x):return KeepTogether([P(n,h2),P(x)])
def table(data,widths):
 t=Table(data,colWidths=widths,repeatRows=1);t.setStyle(TableStyle([('FONT',(0,0),(-1,-1),'Snap',8),('FONT',(0,0),(-1,0),'SnapB',8),('BACKGROUND',(0,0),(-1,0),BLUE),('TEXTCOLOR',(0,0),(-1,0),colors.white),('BACKGROUND',(0,1),(-1,-1),colors.white),('GRID',(0,0),(-1,-1),.4,colors.HexColor('#cddad9')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));return t
def decorate(c,d):
 c.saveState();c.setFillColor(CREAM);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(BLUE);c.rect(0,A4[1]-9*mm,A4[0],9*mm,fill=1,stroke=0);c.setFont('SnapB',8);c.setFillColor(colors.white);c.drawString(18*mm,A4[1]-6*mm,'SYSTEM FOUNDRY / SPLITSNAP');c.setFont('Snap',7);c.setFillColor(MUTED);c.drawRightString(A4[0]-18*mm,10*mm,f'{d.page} / 6');c.restoreState()
doc=SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=18*mm,leftMargin=18*mm,topMargin=20*mm,bottomMargin=17*mm,title='SplitSnap 프로젝트 보고서',author='System Foundry');story=[]
story += [Spacer(1,8*mm),P('SplitSnap',title),P('공동 지출을 정확한 잔액과 간단한 송금안으로 바꾸는<br/>로컬 우선 개인 도구',ParagraphStyle('sub',parent=h1,fontSize=16,leading=23,textColor=BLUE)),Spacer(1,7*mm)]
summary=Table([[P('PERSONAL MVP',small),P('1회 ₩6,900',h1)],[P('상태',small),P('PASS · 테스트 8/8',h2)],[P('종합 평가',small),P('8.4 / 10',h1)]],colWidths=[50*mm,70*mm]);summary.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,-1),colors.white),('BOX',(0,0),(-1,-1),.8,INK),('INNERGRID',(0,0),(-1,-1),.35,colors.HexColor('#cddad9')),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),8),('BOTTOMPADDING',(0,0),(-1,-1),8)]));story += [summary,Spacer(1,7*mm),section('1. 프로젝트 개요','SplitSnap은 친구 여행·모임 지출을 결제자와 실제 분담자 단위로 기록하고, 개인별 잔액과 필요한 송금 목록을 계산하는 로컬 우선 웹 도구다.'),section('2. 대상 고객','2~20명이 함께 여행하거나 행사를 준비하면서 서로 다른 사람이 일부 인원의 비용을 대신 결제하는 개인 모임.'),section('3. 해결하는 문제','결제자가 여러 명이고 지출마다 참여자가 다르면 수작업 정산에서 원 단위 오차와 누락이 생긴다. 송금 횟수가 많으면 정산 완료도 늦어진다.'),PageBreak()]
story += [P('계산 흐름과 구조',title),section('4. 핵심 기능','① 중복 검증 참가자 관리 ② 지출별 결제자·분담자 지정 ③ 잔액 보존과 간소화된 송금안 생성.'),section('5. 사용 방법','참가자를 별칭으로 추가하고 각 지출의 금액, 결제자, 분담자를 선택한다. 하단 잔액을 확인한 뒤 표시된 송금 목록대로 정산한다.'),section('6. 시스템 구조','정적 UI → 입력 검증·원 단위 분배 엔진 → localStorage. 서버, 계정, 외부 결제 또는 환율 API가 없는 단일 브라우저 구조다.'),section('7. 사용 기술','HTML5, CSS, JavaScript, localStorage, Node.js 내장 테스트 러너, Python 정적 서버. PDF는 ReportLab으로 생성했다.'),Spacer(1,6*mm),table([[P('입력',small),P('처리',small),P('출력',small)],[P('참가자·지출·결제자·분담자'),P('정수 원 분배 → 잔액 보존 → 채무·채권 상계'),P('개인 잔액·송금 방향·송금액')]], [50*mm,68*mm,47*mm]),PageBreak()]
story += [P('8. 실행 화면',title),P('Chromium에서 샘플 지출 3건을 불러온 뒤 카페 지출 ₩32,000을 실제로 추가한 1440×1500 화면이다. 총지출 ₩396,000과 송금 3건을 확인했다.'),Spacer(1,4*mm),Image(str(ROOT/'screenshots/dashboard.png'),width=165*mm,height=171.9*mm),Spacer(1,3*mm),P('그림 1. 참가자·공동 지출·송금안·개인 잔액이 결합된 실제 실행 화면',center),PageBreak()]
story += [P('검증과 안전성',title),section('9. 테스트 결과','의존성 설치 성공. 자동 테스트 8/8 통과. HTTP 200과 페이지 제목을 확인했다. Chromium에서 초기 총액 ₩364,000·지출 3건·송금 3건을 확인하고, 신규 지출 후 ₩396,000·4건·송금 3건으로 갱신되는 흐름을 검증했다.'),table([[P('검증 항목',small),P('결과',small)],[P('참가자 중복·인원 범위'),P('PASS')],[P('결제자·분담자 관계'),P('PASS')],[P('금액 범위·정수 검증'),P('PASS')],[P('나누어지지 않는 원 단위 보존'),P('PASS')],[P('잔액 합계 0·송금안'),P('PASS')],[P('HTTP·README·Chromium'),P('PASS')]], [115*mm,50*mm]),Spacer(1,7*mm),section('10. 보안 및 제한사항','실명·계좌번호·카드정보·연락처를 요구하지 않고 별칭과 금액만 브라우저에 저장한다. 입력값을 검증하고 HTML 출력은 이스케이프하며 .env와 자격 증명 패턴을 검사한다. 실제 송금, 외화 환율, 영수증 인식, 다중 기기 동기화는 제공하지 않는다.'),PageBreak()]
story += [P('시장 진입 계획',title),section('11. 가격과 수익 모델','개인용 1회 ₩6,900. 무료판은 참가자 4명·지출 10건으로 제한하고, 구매판은 20명과 JSON 백업을 제공하는 가설이다.'),section('12. 첫 고객 확보 방법','대학생 여행·동아리·수련회 커뮤니티에 “계좌번호 없이 정산 초안 만들기” 데모를 배포한다. 20개 모임에서 완주율, 계산 수정 횟수, 유료 전환 의사를 측정하고 첫 구매 10건을 목표로 한다.'),section('13. 개선 계획','1단계 JSON 백업·복원과 공유용 읽기 전용 요약, 2단계 영수증 이미지 수동 첨부, 3단계 다중 통화 환율을 사용자가 직접 입력하는 기능. 실제 결제·송금 기능은 별도 보안 검토 전 추가하지 않는다.'),Spacer(1,8*mm),table([[P('핵심 가설',small),P('초기 검증 지표',small)],[P('분담자 선택이 계산 누락을 줄인다'),P('정산 후 수정된 지출 수')],[P('송금안이 완료를 앞당긴다'),P('모임 종료→정산 완료 시간')],[P('₩6,900 지불 의사가 있다'),P('체험 20건 중 구매 수')]], [82*mm,83*mm]),PageBreak()]
ratings=[('고객 문제의 강도',8,'반복되는 여행 정산의 불편과 관계 부담이 명확하다.'),('하루 내 완성도',9,'등록·분배·잔액·송금안 흐름을 독립 실행형으로 완성했다.'),('판매 가능성',8,'낮은 1회 가격과 즉시 이해되는 결과 화면이 구매 장벽을 낮춘다.'),('유지보수 난이도',9,'외부 API와 서버가 없어 장애 지점과 운영비가 적다.'),('차별성',8,'지출마다 실제 분담자를 지정하고 원 단위 잔액을 보존한다.'),('확장 가능성',8,'백업·공유 요약·다중 통화로 자연스럽게 확장할 수 있다.')]
story += [P('14. 종합 평가',title),P('평균 8.4 / 10',ParagraphStyle('score',parent=title,fontSize=24,textColor=BLUE)),P('계산 정확성과 사용 흐름이 선명한 개인용 MVP다. 판매 전 실제 모임에서 결과 신뢰도와 입력 피로도를 검증하는 것이 중요하다.'),Spacer(1,5*mm),table([[P('평가 항목',small),P('점수',small),P('근거',small)]]+[[P(a),P(f'{b}/10'),P(c)] for a,b,c in ratings],[42*mm,22*mm,101*mm]),Spacer(1,8*mm),P('최종 판단',h2),P('소규모 유료 테스트 출시 권장. 결제 기능 없이 계산·공유 경험에 집중하고, 실제 모임 20건의 정산 완료 데이터를 기반으로 다음 기능을 결정한다.'),Spacer(1,10*mm),P('Generated and verified on 2026-08-07 · No paid API used',center)]
doc.build(story,onFirstPage=decorate,onLaterPages=decorate);print(OUT)
