(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.RenewalRadar=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  const BILLING=["monthly","yearly"],STATUS=["active","paused","canceled"];
  class ValidationError extends Error{}
  const clean=(value,max,label)=>{const text=String(value??"").trim().replace(/\s+/g," ");if(!text||text.length>max)throw new ValidationError(`${label}을(를) 1~${max}자로 입력하세요.`);return text;};
  const date=value=>{const text=String(value??"");if(!/^\d{4}-\d{2}-\d{2}$/.test(text)||Number.isNaN(Date.parse(`${text}T00:00:00Z`)))throw new ValidationError("갱신일을 확인하세요.");return text;};
  function normalizeSubscription(input){const amount=Number(input.amount);if(!Number.isInteger(amount)||amount<1000||amount>10000000)throw new ValidationError("결제 금액은 1,000~10,000,000원 사이의 정수여야 합니다.");if(!BILLING.includes(input.billing))throw new ValidationError("결제 주기를 확인하세요.");if(!STATUS.includes(input.status))throw new ValidationError("상태를 확인하세요.");return{id:clean(input.id,80,"ID"),name:clean(input.name,50,"서비스명"),category:clean(input.category,30,"분류"),amount,billing:input.billing,status:input.status,renewsOn:date(input.renewsOn)};}
  const daysBetween=(from,to)=>Math.round((Date.parse(`${to}T00:00:00Z`)-Date.parse(`${from}T00:00:00Z`))/86400000);
  function annualCost(item){return item.billing==="monthly"?item.amount*12:item.amount;}
  function urgency(item,today){if(item.status!=="active")return{key:"inactive",rank:4,label:item.status==="paused"?"일시정지":"해지"};const days=daysBetween(today,item.renewsOn);if(days<0)return{key:"overdue",rank:0,label:`${Math.abs(days)}일 지남`};if(days===0)return{key:"today",rank:1,label:"오늘 결제"};if(days<=7)return{key:"soon",rank:2,label:`${days}일 남음`};return{key:"later",rank:3,label:`${days}일 남음`};}
  function buildDashboard(items,today){const normalized=items.map(normalizeSubscription);const decorated=normalized.map(item=>({...item,annualCost:annualCost(item),urgency:urgency(item,today)})).sort((a,b)=>a.urgency.rank-b.urgency.rank||a.renewsOn.localeCompare(b.renewsOn)||a.name.localeCompare(b.name));const active=normalized.filter(x=>x.status==="active"),inactive=normalized.filter(x=>x.status==="canceled");const annual=active.reduce((sum,x)=>sum+annualCost(x),0);return{items:decorated,summary:{active:active.length,dueIn7:active.filter(x=>{const d=daysBetween(today,x.renewsOn);return d>=0&&d<=7;}).length,monthlyEquivalent:Math.round(annual/12),annualCost:annual,canceledSavings:inactive.reduce((sum,x)=>sum+annualCost(x),0)}};}
  function updateStatus(items,id,status){if(!STATUS.includes(status))throw new ValidationError("상태를 확인하세요.");let found=false;const next=items.map(item=>{if(item.id!==id)return item;found=true;return{...item,status};});if(!found)throw new ValidationError("구독을 찾을 수 없습니다.");return next;}
  return{ValidationError,normalizeSubscription,annualCost,urgency,buildDashboard,updateStatus};
});
