(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.PickupEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
const DAY=86400000,STATUSES=['ready','picked_up'];
function cleanText(value,label,max=80){const text=String(value??'').trim().replace(/\s+/g,' ');if(!text||text.length>max)throw new Error(`${label}은(는) 1~${max}자여야 합니다.`);return text}
function number(value,label,min,max){const n=Number(value);if(!Number.isFinite(n)||n<min||n>max)throw new Error(`${label} 범위를 확인하세요.`);return Math.round(n)}
function date(value,label){if(!/^\d{4}-\d{2}-\d{2}$/.test(String(value))||Number.isNaN(Date.parse(`${value}T00:00:00Z`)))throw new Error(`${label} 형식을 확인하세요.`);return String(value)}
function normalize(input){const readyDate=date(input.readyDate,'완료일'),promisedDate=date(input.promisedDate,'수령 약속일');if(promisedDate<readyDate)throw new Error('수령 약속일은 완료일 이후여야 합니다.');const status=String(input.status||'ready');if(!STATUSES.includes(status))throw new Error('상태를 확인하세요.');return{id:cleanText(input.id||`${Date.now()}-${Math.random()}`,'ID',100),ticket:cleanText(input.ticket,'접수번호',30),customer:cleanText(input.customer,'고객 별칭',40),item:cleanText(input.item,'물품',70),readyDate,promisedDate,balance:number(input.balance,'미수금',0,100000000),dailyFee:number(input.dailyFee,'일 보관료',0,1000000),status}}
function daysBetween(from,to){return Math.max(0,Math.floor((Date.parse(`${to}T00:00:00Z`)-Date.parse(`${from}T00:00:00Z`))/DAY))}
function enrich(job,today){const j=normalize(job),waiting=daysBetween(j.readyDate,today),due=daysBetween(today,j.promisedDate),overdue=today>j.promisedDate?daysBetween(j.promisedDate,today):0,storage=Math.max(0,waiting-3)*j.dailyFee;let risk='ontrack';if(overdue>0)risk='overdue';else if(due===0)risk='today';else if(due<=2)risk='soon';return{...j,waiting,overdue,storage,totalDue:j.balance+storage,risk}}
function dashboard(jobs,today){const priority={overdue:0,today:1,soon:2,ontrack:3};const active=jobs.filter(j=>j.status==='ready').map(j=>enrich(j,today));return{readyCount:active.length,overdueCount:active.filter(j=>j.risk==='overdue').length,outstanding:active.reduce((s,j)=>s+j.totalDue,0),storageAccrued:active.reduce((s,j)=>s+j.storage,0),queue:active.sort((a,b)=>priority[a.risk]-priority[b.risk]||b.totalDue-a.totalDue)}}
function updateStatus(jobs,id,status){if(!STATUSES.includes(status))throw new Error('상태를 확인하세요.');let found=false;const next=jobs.map(j=>{if(j.id!==id)return j;found=true;return{...j,status}});if(!found)throw new Error('작업을 찾을 수 없습니다.');return next}
return{normalize,enrich,dashboard,updateStatus,STATUSES};
});
