from pathlib import Path
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

ROOT=Path(__file__).resolve().parents[1]; OUTPUT=ROOT/"report.pdf"; SCREENSHOT=ROOT/"screenshots/dashboard.png"
INK=colors.HexColor("#10192B"); BLUE=colors.HexColor("#3867FF"); SKY=colors.HexColor("#80D7EF"); PALE=colors.HexColor("#E9EDFF"); ORANGE=colors.HexColor("#FF6E59"); MUTED=colors.HexColor("#768096"); LINE=colors.HexColor("#DCD7CD")
pdfmetrics.registerFont(TTFont("Body","/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")); pdfmetrics.registerFont(TTFont("BodyBold","/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"))
TITLE=ParagraphStyle("title",fontName="BodyBold",fontSize=31,leading=35,textColor=INK,spaceAfter=8); SUB=ParagraphStyle("sub",fontName="Body",fontSize=11,leading=17,textColor=MUTED,spaceAfter=8); EYE=ParagraphStyle("eye",fontName="BodyBold",fontSize=8,leading=10,textColor=BLUE,spaceAfter=6); H1=ParagraphStyle("h1",fontName="BodyBold",fontSize=18,leading=22,textColor=INK,spaceAfter=7); H2=ParagraphStyle("h2",fontName="BodyBold",fontSize=12,leading=15,textColor=INK,spaceAfter=4); BODY=ParagraphStyle("body",fontName="Body",fontSize=9.2,leading=14,textColor=colors.HexColor("#35415B"),spaceAfter=7); SMALL=ParagraphStyle("small",fontName="Body",fontSize=7.5,leading=10,textColor=MUTED); WHITE=ParagraphStyle("white",fontName="BodyBold",fontSize=9,leading=13,textColor=colors.white)

def frame(canvas,doc):
    canvas.saveState(); w,h=A4; canvas.setFillColor(INK); canvas.rect(0,h-12*mm,w,12*mm,stroke=0,fill=1); canvas.setFillColor(SKY); canvas.setFont("BodyBold",8); canvas.drawString(18*mm,h-7.6*mm,"GEARLEDGER / SYSTEM FOUNDRY"); canvas.setFillColor(MUTED); canvas.setFont("Body",7); canvas.drawString(18*mm,10*mm,"2026-08-05 / BUSINESS MVP REPORT"); canvas.drawRightString(w-18*mm,10*mm,str(doc.page)); canvas.restoreState()
def section(n,title,text): return [Paragraph(f"{n:02d} / {title.upper()}",EYE),Paragraph(title,H1),Paragraph(text,BODY)]
def card(title,value,note,accent):
    vs=ParagraphStyle("value",fontName="BodyBold",fontSize=22,leading=27,textColor=INK); t=Table([[Paragraph(title.upper(),SMALL)],[Paragraph(value,vs)],[Paragraph(note,SMALL)]],colWidths=[50*mm]); t.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),colors.white),("BOX",(0,0),(-1,-1),.8,LINE),("LINEABOVE",(0,0),(-1,0),4,accent),("LEFTPADDING",(0,0),(-1,-1),10),("RIGHTPADDING",(0,0),(-1,-1),10),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)])); return t

story=[Spacer(1,10*mm),Paragraph("SYSTEM FOUNDRY / BUSINESS MVP",EYE),Paragraph("GearLedger",TITLE),Paragraph("A local-first return queue that keeps shared equipment, deadlines, condition, and value visible.",SUB),Spacer(1,12*mm)]
story.append(Table([[card("Product status","PASS","Implemented and verified",SKY),card("Automated tests","8 / 8","Zero failures",ORANGE),card("Monthly price","KRW 22K","Per workspace",BLUE)]],colWidths=[55*mm]*3)); story+=[Spacer(1,13*mm)]
story+=section(1,"Project overview","GearLedger lets a small creative workspace register equipment checkouts, work from an overdue-first return queue, and separate available, returned, and maintenance value without deploying a full asset-management suite.")
story+=section(2,"Target customer","Photo and video studios, music rooms, maker spaces, and small education labs with two to ten operators sharing valuable portable equipment.")
story+=section(3,"Problem","When checkout details live in chat messages or memory, equipment becomes overdue, staff cannot tell what is available, and damaged items may be loaned again before inspection. The financial exposure stays invisible."); story.append(PageBreak())

story += [Paragraph("PRODUCT",EYE),Paragraph("Three focused jobs",TITLE)] + section(4,"Core features","The MVP implements one complete equipment return loop:")
features=[["01",Paragraph("<b>Validated equipment checkout</b><br/>Capture asset, category, borrower alias, value, due date, checkout status, and condition with strict limits.",BODY)],["02",Paragraph("<b>Return urgency queue</b><br/>Order overdue, today, upcoming, maintenance, and returned records around the next operational action.",BODY)],["03",Paragraph("<b>Value and condition control</b><br/>Total checked-out, maintenance, and returned asset value while keeping condition attached to every record.",BODY)]]
ft=Table(features,colWidths=[14*mm,150*mm]); ft.setStyle(TableStyle([("BACKGROUND",(0,0),(0,-1),INK),("TEXTCOLOR",(0,0),(0,-1),SKY),("FONTNAME",(0,0),(0,-1),"BodyBold"),("ALIGN",(0,0),(0,-1),"CENTER"),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("GRID",(0,0),(-1,-1),.5,LINE),("TOPPADDING",(0,0),(-1,-1),9),("BOTTOMPADDING",(0,0),(-1,-1),9),("LEFTPADDING",(1,0),(1,-1),12)])); story += [ft,Spacer(1,7*mm)]
story+=section(5,"How to use","At handoff, register the asset with a non-identifying team or project alias and a return date. Process overdue and today items first. On return, set the condition to good, check, or repair; move unavailable equipment to maintenance before another checkout.")
story+=section(6,"System architecture","A static browser UI calls pure validation, urgency, and aggregation functions and persists state only in localStorage. Node tests exercise the same module. No account, backend, database, analytics, or external API is used.")
arch=Table([["Browser UI","Ledger module","Local storage","Node tests"],["HTML + CSS","Rules + totals","Device-only data","Pure functions"]],colWidths=[41*mm]*4); arch.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTSIZE",(0,0),(-1,-1),8),("ALIGN",(0,0),(-1,-1),"CENTER"),("GRID",(0,0),(-1,-1),.6,LINE),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8)])); story += [arch,Spacer(1,5*mm)]
story+=section(7,"Technology","Static HTML, responsive CSS, vanilla JavaScript, localStorage, bundled Noto Sans KR fonts, and the built-in Node.js test runner. Runtime dependencies: zero. Paid APIs: zero."); story.append(PageBreak())

story += [Paragraph("VALIDATED INTERFACE",EYE),Paragraph("Actual running screen",TITLE),Paragraph("Captured from headless Chromium after a tripod checkout was validated and added.",SUB),Spacer(1,4*mm),Image(str(SCREENSHOT),width=160*mm,height=158*mm),Spacer(1,4*mm)]
story+=section(8,"Running screen","The verified screen shows four checked-out assets, one overdue return, KRW 3.85M value out, and KRW 780K in maintenance after adding a KRW 320K tripod. Marking that tripod returned restored value out to KRW 3.53M and raised returned value to KRW 1.62M."); story.append(PageBreak())

story += [Paragraph("VERIFICATION",EYE),Paragraph("Evidence, not assumptions",TITLE)] + section(9,"Test results","Every required check was executed against the generated project.")
checks=[["Check","Result","Evidence"],["Dependency installation","PASS","npm install completed; zero runtime dependencies"],["Application start","PASS","README HTTP server returned status 200"],["Core workflow","PASS","Value out KRW 3.53M to 3.85M to 3.53M"],["Automated tests","8 / 8","Validation, urgency, totals, status, condition"],["README commands","PASS","Install, test, and start commands executed"],["Credential scan","PASS","No secret patterns and no .env file"],["PDF","PASS","Generated, parsed, rendered, visually inspected"]]
tt=Table(checks,colWidths=[48*mm,23*mm,94*mm],repeatRows=1); tt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTNAME",(1,1),(1,-1),"BodyBold"),("TEXTCOLOR",(1,1),(1,-1),BLUE),("FONTSIZE",(0,0),(-1,-1),7.5),("GRID",(0,0),(-1,-1),.5,LINE),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),7),("BOTTOMPADDING",(0,0),(-1,-1),7)])); story += [tt,Spacer(1,8*mm)]
story+=section(10,"Security and limitations","GearLedger sends no data outside the browser and encourages team or project aliases rather than personal contact details. Text, value, date, status, and condition inputs are validated; displayed text is HTML-escaped. Device-local data is unencrypted and disappears when browser storage is cleared. The MVP has no barcode scanning, photo evidence, notifications, audit history, or multi-user access."); story.append(PageBreak())

story += [Paragraph("GO TO MARKET",EYE),Paragraph("Protect one asset before it goes missing",TITLE)]
story+=section(11,"Pricing and revenue model","Charge KRW 22,000 per workspace per month for local use and updates. Preventing one delayed production or identifying one maintenance issue early can exceed the annual subscription cost. The MVP itself has no hosting or paid-service dependency.")
story+=section(12,"First customer acquisition","Recruit fifteen photo studios, rehearsal rooms, maker spaces, and school media labs through local operator communities. Load their ten most frequently shared items and run a two-week return-control trial. Convert by measuring overdue count, unavailable time, and value protected.")
story+=section(13,"Improvement plan","Priorities after observing real handoff routines:")
for item in ["JSON backup and restore for device migration.","Printable QR labels for faster local record lookup.","Optional return reminders and condition-photo attachments.","Encrypted sync, roles, and immutable audit history after team demand is proven."]: story.append(Paragraph(f"<font color='#3867FF'>●</font> {item}",BODY))
story += [Spacer(1,7*mm),Paragraph("PRODUCT BOUNDARY",H2),Paragraph("GearLedger should remain an operational checkout tool. It should not store unnecessary personal data, claim to replace insurance or legal agreements, or expose a shared asset register without access control.",BODY)]; story.append(PageBreak())

story += [Paragraph("ASSESSMENT",EYE),Paragraph("Overall evaluation",TITLE)] + section(14,"Overall score","Six dimensions are scored out of 10. A higher maintenance score means easier maintenance.")
ratings=[("Customer problem strength",8,"Overdue or unavailable equipment directly disrupts paid work."),("One-day completeness",9,"The checkout, prioritize, return, and condition loop is tested."),("Sales potential",8,"Protected asset value gives a concrete subscription value case."),("Maintenance difficulty",9,"Zero runtime dependencies and no backend keep maintenance light."),("Differentiation",8,"Value exposure and condition status sharpen a generic checkout list."),("Scalability",8,"QR labels, photos, reminders, roles, and audit history can expand it.")]
rows=[["Dimension","Score","Rationale"]]+[[n,f"{s}/10",r] for n,s,r in ratings]; rt=Table(rows,colWidths=[52*mm,20*mm,93*mm]); rt.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,0),INK),("TEXTCOLOR",(0,0),(-1,0),colors.white),("FONTNAME",(0,0),(-1,0),"BodyBold"),("FONTNAME",(0,1),(-1,-1),"Body"),("FONTNAME",(1,1),(1,-1),"BodyBold"),("BACKGROUND",(1,1),(1,-1),PALE),("FONTSIZE",(0,0),(-1,-1),7.4),("GRID",(0,0),(-1,-1),.5,LINE),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8)])); story += [rt,Spacer(1,11*mm)]
big=ParagraphStyle("big",fontName="BodyBold",fontSize=21,leading=25,textColor=SKY); overall=Table([[Paragraph("OVERALL",WHITE),Paragraph("8.3 / 10",big),Paragraph("Proceed to a fifteen-workspace return-control trial.",WHITE)]],colWidths=[28*mm,48*mm,89*mm]); overall.setStyle(TableStyle([("BACKGROUND",(0,0),(-1,-1),INK),("VALIGN",(0,0),(-1,-1),"MIDDLE"),("LEFTPADDING",(0,0),(-1,-1),12),("RIGHTPADDING",(0,0),(-1,-1),12),("TOPPADDING",(0,0),(-1,-1),14),("BOTTOMPADDING",(0,0),(-1,-1),14)])); story += [overall,Spacer(1,10*mm),Paragraph("Verdict: technically complete and visually polished for a business MVP. The next useful evidence is whether overdue count and unavailable equipment time fall during a real two-week trial.",BODY)]

doc=SimpleDocTemplate(str(OUTPUT),pagesize=A4,leftMargin=18*mm,rightMargin=18*mm,topMargin=20*mm,bottomMargin=18*mm,title="GearLedger MVP Report",author="System Foundry",subject="Business MVP implementation and validation report"); doc.build(story,onFirstPage=frame,onLaterPages=frame); print(f"Generated {OUTPUT}")
