(function(root,factory){const api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.SplitEngine=api})(typeof globalThis!=='undefined'?globalThis:this,function(){
function text(v,label,max=40){const s=String(v??'').trim().replace(/\s+/g,' ');if(!s||s.length>max)throw new Error(`${label}은(는) 1~${max}자여야 합니다.`);return s}
function normalizePeople(values){const people=values.map(v=>text(v,'참가자')).filter(Boolean);if(people.length<2||people.length>20)throw new Error('참가자는 2~20명이어야 합니다.');if(new Set(people).size!==people.length)throw new Error('참가자 이름은 중복될 수 없습니다.');return people}
function normalizeExpense(input,people){const title=text(input.title,'지출명',60),payer=text(input.payer,'결제자'),amount=Number(input.amount),members=[...new Set(input.members||[])];if(!people.includes(payer))throw new Error('결제자가 참가자에 없습니다.');if(!Number.isInteger(amount)||amount<1||amount>100000000)throw new Error('금액은 1~100,000,000원 정수여야 합니다.');if(!members.length||members.some(x=>!people.includes(x)))throw new Error('분담자를 확인하세요.');return{id:text(input.id||`${Date.now()}-${Math.random()}`,'ID',100),title,payer,amount,members}}
function balances(people,expenses){const out=Object.fromEntries(people.map(p=>[p,0]));for(const raw of expenses){const e=normalizeExpense(raw,people),base=Math.floor(e.amount/e.members.length),remainder=e.amount%e.members.length;out[e.payer]+=e.amount;e.members.forEach((p,i)=>out[p]-=base+(i<remainder?1:0))}return out}
function settlements(balanceMap){const debtors=[],creditors=[];for(const [person,value] of Object.entries(balanceMap)){if(value<0)debtors.push({person,amount:-value});if(value>0)creditors.push({person,amount:value})}debtors.sort((a,b)=>b.amount-a.amount);creditors.sort((a,b)=>b.amount-a.amount);const result=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const amount=Math.min(debtors[i].amount,creditors[j].amount);if(amount)result.push({from:debtors[i].person,to:creditors[j].person,amount});debtors[i].amount-=amount;creditors[j].amount-=amount;if(!debtors[i].amount)i++;if(!creditors[j].amount)j++}return result}
function summary(people,expenses){const b=balances(people,expenses);return{total:expenses.reduce((s,e)=>s+Number(e.amount),0),balances:b,settlements:settlements(b)}}
return{normalizePeople,normalizeExpense,balances,settlements,summary};
});
