from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
GREEN=HexColor('#245b42');INK=HexColor('#162319');MUTED=HexColor('#687068');PAPER=HexColor('#f6f4ed');LINE=HexColor('#d7d9d0')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=GREEN,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=GREEN,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(GREEN);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'CareCycle · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · PERSONAL MVP','c'),Spacer(1,20),p('CareCycle','t'),Spacer(1,10),p('가정 관리 주기를 놓치지 않도록<br/>오늘 할 일을 먼저 보여 주는 로컬 우선 도구','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-09-0902-carecycle')],[p('대상 고객'),p('필터·가전·취미 장비를 직접 관리하는 개인')],[p('가격'),p('1회 ₩9,900')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,GREEN),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','CareCycle은 반복되는 집 안 유지관리 항목의 다음 기한과 비용을 계산해 우선순위대로 보여 주는 브라우저 기반 개인 도구다.'),sec('2. 대상 고객','공기청정기·에어컨 필터, 생활가전, 취미 장비를 여러 개 보유하고 직접 관리하는 1~3인 가구다.'),sec('3. 해결하는 문제','관리 주기가 메모와 기억에 흩어지면 필터 교체와 청소를 늦추거나 필요 이상 자주 소모품을 구매한다. 일정과 비용을 함께 보면 불필요한 지출과 관리 공백을 줄일 수 있다.'),sec('4. 핵심 기능','① 검증된 관리 항목 등록 ② 지연·7일·30일 기준 우선순위와 연간 비용 ③ 완료 시 다음 관리일 자동 계산'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 항목과 최근 완료일, 반복 주기를 등록하고 큐를 확인한 뒤 완료 버튼으로 다음 일정을 갱신한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·주기 계산 엔진 → localStorage. 서버 계정이나 외부 데이터 전송이 없는 단일 사용자 구조다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 새 관리 항목을 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 날짜 계산, 입력 정제와 범위 검증, 지연·긴급 판정, 큐 정렬, 완료 처리를 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 길이·숫자 범위 제한과 HTML 이스케이프를 적용한다. 비밀값과 외부 전송은 없다. 브라우저를 초기화하면 데이터가 삭제되며, 안전 설비는 제조사·전문가 지침을 우선해야 한다.'),sec('11. 가격과 수익 모델','1회 ₩9,900 라이선스. 로컬 저장과 간단한 반복 일정 계산을 판매 포인트로 삼고, 향후 선택형 백업 기능을 별도 업그레이드로 제공한다.'),sec('12. 첫 고객 확보 방법','살림·1인 가구·메이커 커뮤니티에 무료 가정관리 체크리스트를 배포하고, 관리 항목이 5개 이상인 사용자를 유료 버전으로 전환한다.'),sec('13. 개선 계획','1) JSON 백업 2) 브라우저 알림 3) 계절별 템플릿 4) 완료 이력 차트 5) 선택형 암호화 동기화.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('8/10'),p('반복되는 관리 공백과 소모품 비용이 분명하다.')],[p('하루 내 완성도'),p('9/10'),p('등록·우선순위·완료 흐름을 완성했다.')],[p('판매 가능성'),p('8/10'),p('저가 1회 구매와 로컬 저장의 가치가 명확하다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('7/10'),p('일정과 연 환산 비용을 한 화면에 결합한다.')],[p('확장 가능성'),p('8/10'),p('알림·템플릿·이력으로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),GREEN),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.2/10','h'),p('명확한 반복 문제를 외부 서비스 없이 해결하는 완성도 높은 개인용 MVP다. 판매 전에는 사용자가 실제로 관리하는 항목 수와 알림 필요성을 인터뷰로 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 개인 로컬 사용과 고객 인터뷰용 데모로 사용할 수 있다. 안전 관련 장비는 공식 지침을 대체하지 않는다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='CareCycle MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
