(function(root,factory){const api=factory();if(typeof module==="object"&&module.exports)module.exports=api;else root.GearLedger=api;})(typeof globalThis!=="undefined"?globalThis:this,function(){
  const STATUS=["out","returned","maintenance"],CONDITION=["good","check","repair"];
  class ValidationError extends Error{}
  const clean=(value,max,label)=>{const text=String(value??"").trim().replace(/\s+/g," ");if(!text||text.length>max)throw new ValidationError(`${label}을(를) 1~${max}자로 입력하세요.`);return text;};
  const date=value=>{const text=String(value??"");if(!/^\d{4}-\d{2}-\d{2}$/.test(text)||Number.isNaN(Date.parse(`${text}T00:00:00Z`)))throw new ValidationError("반납 예정일을 확인하세요.");return text;};
  function normalizeLoan(input){const value=Number(input.assetValue);if(!Number.isInteger(value)||value<10000||value>100000000)throw new ValidationError("장비 가액은 10,000~100,000,000원 사이의 정수여야 합니다.");if(!STATUS.includes(input.status))throw new ValidationError("대여 상태를 확인하세요.");if(!CONDITION.includes(input.condition))throw new ValidationError("장비 상태를 확인하세요.");return{id:clean(input.id,80,"ID"),asset:clean(input.asset,60,"장비명"),category:clean(input.category,30,"분류"),borrowerAlias:clean(input.borrowerAlias,40,"대여자 별칭"),assetValue:value,dueOn:date(input.dueOn),status:input.status,condition:input.condition};}
  const days=(from,to)=>Math.round((Date.parse(`${to}T00:00:00Z`)-Date.parse(`${from}T00:00:00Z`))/86400000);
  function urgency(item,today){if(item.status==="maintenance")return{key:"maintenance",rank:4,label:"점검 중"};if(item.status==="returned")return{key:"returned",rank:5,label:"반납 완료"};const d=days(today,item.dueOn);if(d<0)return{key:"overdue",rank:0,label:`${Math.abs(d)}일 연체`};if(d===0)return{key:"today",rank:1,label:"오늘 반납"};if(d<=3)return{key:"soon",rank:2,label:`${d}일 남음`};return{key:"later",rank:3,label:`${d}일 남음`};}
  function buildDashboard(items,today){const normalized=items.map(normalizeLoan),decorated=normalized.map(x=>({...x,urgency:urgency(x,today)})).sort((a,b)=>a.urgency.rank-b.urgency.rank||a.dueOn.localeCompare(b.dueOn)||a.asset.localeCompare(b.asset));const out=normalized.filter(x=>x.status==="out"),maintenance=normalized.filter(x=>x.status==="maintenance"),returned=normalized.filter(x=>x.status==="returned");return{items:decorated,summary:{outCount:out.length,overdue:out.filter(x=>days(today,x.dueOn)<0).length,outValue:out.reduce((s,x)=>s+x.assetValue,0),maintenanceValue:maintenance.reduce((s,x)=>s+x.assetValue,0),returnedValue:returned.reduce((s,x)=>s+x.assetValue,0)}};}
  function updateLoan(items,id,status,condition){if(!STATUS.includes(status)||!CONDITION.includes(condition))throw new ValidationError("상태를 확인하세요.");let found=false;const next=items.map(x=>{if(x.id!==id)return x;found=true;return{...x,status,condition};});if(!found)throw new ValidationError("대여 기록을 찾을 수 없습니다.");return next;}
  return{ValidationError,normalizeLoan,urgency,buildDashboard,updateLoan};
});
