from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor,white
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.platypus import SimpleDocTemplate,Paragraph,Spacer,Image,Table,TableStyle,PageBreak,KeepTogether
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
R=Path(__file__).resolve().parents[1];pdfmetrics.registerFont(TTFont('Noto',R/'app/fonts/noto-sans-kr-regular.ttf'));pdfmetrics.registerFont(TTFont('NotoB',R/'app/fonts/noto-sans-kr-bold.ttf'))
TEAL=HexColor('#176b67');INK=HexColor('#1b221f');MUTED=HexColor('#66736f');PAPER=HexColor('#f5f3ed');LINE=HexColor('#d3d9d6')
S={'t':ParagraphStyle('t',fontName='NotoB',fontSize=30,leading=38,textColor=INK),'h':ParagraphStyle('h',fontName='NotoB',fontSize=19,leading=26,textColor=TEAL,spaceBefore=6,spaceAfter=10),'b':ParagraphStyle('b',fontName='Noto',fontSize=9.3,leading=15,textColor=INK,spaceAfter=8),'s':ParagraphStyle('s',fontName='Noto',fontSize=7.5,leading=11,textColor=MUTED),'c':ParagraphStyle('c',fontName='NotoB',fontSize=11,leading=17,textColor=TEAL,alignment=TA_CENTER)}
def p(x,k='b'):return Paragraph(x,S[k])
def sec(a,b):return KeepTogether([p(a,'h'),p(b)])
def hf(c,d):c.saveState();c.setFillColor(PAPER);c.rect(0,0,A4[0],A4[1],fill=1,stroke=0);c.setFillColor(TEAL);c.rect(0,A4[1]-8,A4[0],8,fill=1,stroke=0);c.setFont('Noto',7);c.setFillColor(MUTED);c.drawString(42,24,'DockDiff · System Foundry MVP Report');c.drawRightString(A4[0]-42,24,str(d.page));c.restoreState()
st=[Spacer(1,90),p('SYSTEM FOUNDRY · BUSINESS MVP','c'),Spacer(1,20),p('DockDiff','t'),Spacer(1,10),p('주문과 실수령의 차이를 잡아<br/>회수 금액과 기한을 관리하는 업무 도구','c'),Spacer(1,35)]
t=Table([[p('프로젝트'),p('2026-08-10-1613-dockdiff')],[p('대상 고객'),p('소형 카페·소매점·제작사')],[p('가격'),p('사업장당 월 ₩18,000')],[p('상태'),p('PASS · 자동 테스트 8/8')]],colWidths=[100,350]);t.setStyle(TableStyle([('BOX',(0,0),(-1,-1),1,TEAL),('INNERGRID',(0,0),(-1,-1),.5,LINE),('BACKGROUND',(0,0),(-1,-1),white),('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(-1,-1),10),('TOPPADDING',(0,0),(-1,-1),10),('BOTTOMPADDING',(0,0),(-1,-1),10)]));st += [t,PageBreak()]
st += [sec('1. 프로젝트 개요','DockDiff는 발주 수량과 실수령 수량을 대조해 부족 수량, 회수 대상액, 이의 제기 기한을 계산하는 브라우저 기반 업무 도구다.'),sec('2. 대상 고객','여러 거래처에서 식자재·포장재·재료를 정기적으로 납품받는 소형 카페, 소매점, 인쇄·제작 사업장이다.'),sec('3. 해결하는 문제','바쁜 입고 시간에 수량 차이를 메모만 하면 환불·재납품 요청 기한을 놓치기 쉽다. 부족 금액과 남은 기한을 큐로 보여 주면 회수 업무를 우선 처리할 수 있다.'),sec('4. 핵심 기능','① 검증된 납품 대조 등록 ② 부족 수량·회수 대상액·기한 위험도 계산 ③ 거래처 처리 완료 상태 추적'),sec('5. 사용 방법','npm install, npm test, npm start 순서로 실행한다. 발주와 실수령 수량을 등록하고 위험 큐를 확인한 뒤 환불·재납품이 끝난 기록을 완료 처리한다.'),PageBreak()]
st += [sec('6. 시스템 구조','브라우저 화면 → 입력 검증·금액·기한 계산 엔진 → localStorage. 거래처 계정이나 외부 데이터 전송이 없는 단일 사업장 구조다.'),sec('7. 사용 기술','HTML5, CSS, 순수 JavaScript, Node.js 내장 테스트 러너, Python 정적 서버, Docker. 외부 유료 API와 런타임 패키지는 없다.'),p('8. 실행 화면','h'),Image(str(R/'screenshots/dashboard.png'),width=493,height=493*1500/1440),p('실제 Chromium에서 신규 납품 대조 기록을 추가한 뒤 캡처한 화면.','s'),PageBreak()]
st += [sec('9. 테스트 결과','자동 테스트 8/8 통과. 날짜 계산, 입력 정제와 범위 검증, 부족 금액, 기한 위험, 회수액 합산, 완료 토글을 확인했다. HTTP 200, Chromium 핵심 흐름, README 명령도 검증했다.'),sec('10. 보안 및 제한사항','입력 길이·수량·금액 범위 제한과 HTML 이스케이프를 적용한다. 비밀값과 외부 전송은 없다. 회계·법률 판단, 증빙 파일 보관, 거래처 자동 연락은 포함하지 않는다.'),sec('11. 가격과 수익 모델','사업장당 월 ₩18,000 구독. 놓치기 쉬운 납품 차액을 회수하고 입고 대조를 표준화하는 가치를 판매 포인트로 삼는다.'),sec('12. 첫 고객 확보 방법','소형 카페·공방 10곳에 무료 입고 대조 템플릿을 제공하고, 최근 한 달 납품 5건을 함께 입력해 14일 체험으로 전환한다.'),sec('13. 개선 계획','1) CSV 가져오기 2) 증빙 사진 첨부 3) 거래처별 성과 4) 담당자와 알림 5) 회계 프로그램 내보내기.'),PageBreak()]
data=[[p('평가 항목'),p('점수'),p('근거')],[p('고객 문제의 강도'),p('9/10'),p('납품 차이는 직접적인 비용 손실이다.')],[p('하루 내 완성도'),p('9/10'),p('등록·금액·기한·완료 흐름을 완성했다.')],[p('판매 가능성'),p('8/10'),p('회수 금액으로 구독 가치를 설명하기 쉽다.')],[p('유지보수 난이도'),p('9/10'),p('정적 앱이며 외부 서비스가 없다.')],[p('차별성'),p('7/10'),p('수량 차이와 이의 기한을 함께 관리한다.')],[p('확장 가능성'),p('8/10'),p('증빙·거래처 평가·회계 연동으로 확장 가능하다.')]];q=Table(data,colWidths=[105,48,340]);q.setStyle(TableStyle([('BACKGROUND',(0,0),(-1,0),TEAL),('TEXTCOLOR',(0,0),(-1,0),white),('GRID',(0,0),(-1,-1),.5,LINE),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),6),('BOTTOMPADDING',(0,0),(-1,-1),6)]));st += [p('14. 종합 평가','h'),q,Spacer(1,16),p('종합 점수 8.3/10','h'),p('작은 사업장의 직접적인 비용 누수를 좁은 기능으로 해결한다. 유료화 전에는 실제 납품 차이 빈도와 거래처별 기한 관리 수요를 확인해야 한다.'),PageBreak(),p('부록 · 검증 체크리스트','h'),p('✓ 의존성 설치  ✓ 프로그램 시작  ✓ 핵심 기능  ✓ 자동 테스트 8개  ✓ README 명령  ✓ 비밀정보 검사  ✓ PDF 생성·파싱·렌더링'),p('릴리스 판정','h'),p('<b>PASS</b> — 소형 사업장의 내부 사용과 고객 인터뷰용 데모로 사용할 수 있다. 실제 기한은 발주서와 거래처 약관을 확인해야 한다.')]
SimpleDocTemplate(str(R/'report.pdf'),pagesize=A4,rightMargin=42,leftMargin=42,topMargin=36,bottomMargin=40,title='DockDiff MVP Report',author='System Foundry').build(st,onFirstPage=hf,onLaterPages=hf)
print(R/'report.pdf')
